### ISSUE TITLE
[Bug] Gradle failed to fetch dependencies and Resolution failed in Resolving Android Dependencies

### ISSUE THREAD

**Issue by martymayfly** [firebase/quickstart-unity#1057]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.5f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: FirebaseAnalytics.unitypackage (dotnet4)
  * Problematic Firebase Component: Analytics 
  * Other Firebase Components in use: - 
  * Additional SDKs you are using: - 
  * Platform you are using the Unity editor on: Mac 
  * Platform you are targeting: android 
  * Scripting Runtime: .Net4x - Mono

### [REQUIRED] Please describe the issue here:

I have a problem about Resolving Android Dependencies. I have a firebase project, I added the googleservices.json under my assets folder and have the same bundle id. 
I imported the FirebaseAnalytics.unitypackage for dotnet4 and after that Resolving Android Dependencies starts and after a while it gives errors on console (Gradle failed to fetch dependencies and Resolution failed) Details are listed below.
I am looking for a solution but nothing is helpful.

--- Details for Gradle failed to fetch dependencies
Gradle failed to fetch dependencies.

Failed to run '/Users/martymayfly/Documents/unity_projects/quickstart-unity-master/analytics/testapp/Temp/PlayServicesResolverGradle/gradlew --no-daemon -b "/Users/martymayfly/Documents/unity_projects/quickstart-unity-master/analytics/testapp/Temp/PlayServicesResolverGradle/PlayServicesResolver.scripts.download_artifacts.gradle" "-PANDROID_HOME=/Applications/Unity/Hub/Editor/2020.3.5f1/PlaybackEngines/AndroidPlayer/SDK" "-PTARGET_DIR=/Users/martymayfly/Documents/unity_projects/quickstart-unity-master/analytics/testapp/Assets/Plugins/Android" "-PMAVEN_REPOS=file:////Users/martymayfly/Documents/unity_projects/quickstart-unity-master/analytics/testapp/Assets/Firebase/m2repository" "-PPACKAGES_TO_COPY=com.google.firebase:firebase-analytics:18.0.3;com.google.firebase:firebase-analytics-unity:7.2.0;com.google.firebase:firebase-common:19.5.0;com.google.android.gms:play-services-base:17.6.0;com.google.firebase:firebase-app-unity:7.2.0" "-PUSE_JETIFIER=0" "-PDATA_BINDING_VERSION=3.6.0"'
stdout:

> Configure project :
ANDROID_HOME: /Applications/Unity/Hub/Editor/2020.3.5f1/PlaybackEngines/AndroidPlayer/SDK
MAVEN_REPOS: name=Google url=https://dl.google.com/dl/android/maven2/
MAVEN_REPOS: name=maven url=https://dl.google.com/dl/android/maven2/
MAVEN_REPOS: name=maven2 url=file:/Users/martymayfly/Documents/unity_projects/quickstart-unity-master/analytics/testapp/Assets/Firebase/m2repository/
MAVEN_REPOS: name=MavenLocal url=file:/Users/martymayfly/.m2/repository
MAVEN_REPOS: name=BintrayJCenter url=https://jcenter.bintray.com/
MAVEN_REPOS: name=MavenRepo url=https://repo.maven.apache.org/maven2/
PACKAGES_TO_COPY: com.google.firebase:firebase-analytics:18.0.3
PACKAGES_TO_COPY: com.google.firebase:firebase-analytics-unity:7.2.0
PACKAGES_TO_COPY: com.google.firebase:firebase-common:19.5.0
PACKAGES_TO_COPY: com.google.android.gms:play-services-base:17.6.0
PACKAGES_TO_COPY: com.google.firebase:firebase-app-unity:7.2.0
TARGET_DIR: /Users/martymayfly/Documents/unity_projects/quickstart-unity-master/analytics/testapp/Assets/Plugins/Android

> Configure project :
Resolution attempt 1: packages [com.google.firebase:firebase-analytics-unity:7.2.0@srcaar, com.google.firebase:firebase-app-unity:7.2.0@srcaar, com.google.firebase:firebase-analytics:18.0.3, com.google.android.gms:play-services-base:17.6.0, com.google.firebase:firebase-common:19.5.0]

> Configure project :
Resolution attempt: 1, conflicts detected: false, updated packages: false

> Configure project :
version locked packages: []
non-version locked packages: [com.google.firebase:firebase-analytics-unity:7.2.0@srcaar, com.google.firebase:firebase-app-unity:7.2.0@srcaar, com.google.firebase:firebase-analytics:18.0.3, com.google.android.gms:play-services-base:17.6.0, com.google.firebase:firebase-common:19.5.0]

> Task :copyPackages
Copied artifacts:
androidx.annotation.annotation-1.1.0.jar
androidx.arch.core.core-common-2.0.0.jar
androidx.arch.core.core-runtime-2.0.0.aar
androidx.asynclayoutinflater.asynclayoutinflater-1.0.0.aar
androidx.collection.collection-1.0.0.jar
androidx.coordinatorlayout.coordinatorlayout-1.0.0.aar
androidx.core.core-1.2.0.aar
androidx.cursoradapter.cursoradapter-1.0.0.aar
androidx.customview.customview-1.0.0.aar
androidx.documentfile.documentfile-1.0.0.aar
androidx.drawerlayout.drawerlayout-1.0.0.aar
androidx.fragment.fragment-1.0.0.aar
androidx.interpolator.interpolator-1.0.0.aar
androidx.legacy.legacy-support-core-ui-1.0.0.aar
androidx.legacy.legacy-support-core-utils-1.0.0.aar
androidx.lifecycle.lifecycle-common-2.0.0.jar
androidx.lifecycle.lifecycle-livedata-2.0.0.aar
androidx.lifecycle.lifecycle-livedata-core-2.0.0.aar
androidx.lifecycle.lifecycle-runtime-2.0.0.aar
androidx.lifecycle.lifecycle-viewmodel-2.0.0.aar
androidx.loader.loader-1.0.0.aar
androidx.localbroadcastmanager.localbroadcastmanager-1.0.0.aar
androidx.print.print-1.0.0.aar
androidx.slidingpanelayout.slidingpanelayout-1.0.0.aar
androidx.swiperefreshlayout.swiperefreshlayout-1.0.0.aar
androidx.versionedparcelable.versionedparcelable-1.1.0.aar
androidx.viewpager.viewpager-1.0.0.aar
com.google.android.gms.play-services-ads-identifier-17.0.0.aar
com.google.android.gms.play-services-base-17.6.0.aar
com.google.android.gms.play-services-basement-17.6.0.aar
com.google.android.gms.play-services-measurement-18.0.3.aar
com.google.android.gms.play-services-measurement-api-18.0.3.aar
com.google.android.gms.play-services-measurement-base-18.0.3.aar
com.google.android.gms.play-services-measurement-impl-18.0.3.aar
com.google.android.gms.play-services-measurement-sdk-18.0.3.aar
com.google.android.gms.play-services-measurement-sdk-api-18.0.3.aar
com.google.android.gms.play-services-stats-17.0.0.aar
com.google.android.gms.play-services-tasks-17.2.1.aar
com.google.firebase.firebase-analytics-18.0.3.aar
com.google.firebase.firebase-analytics-unity-7.2.0.aar
com.google.firebase.firebase-annotations-16.0.0.jar
com.google.firebase.firebase-app-unity-7.2.0.aar
com.google.firebase.firebase-common-19.5.0.aar
com.google.firebase.firebase-components-16.1.0.aar
com.google.firebase.firebase-installations-16.3.2.aar
com.google.firebase.firebase-installations-interop-16.0.0.aar
com.google.firebase.firebase-measurement-connector-18.0.0.aar

BUILD SUCCESSFUL in 2m 59s
1 actionable task: 1 executed

stderr:
Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2@11eb4027.
java.lang.StackOverflowError
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:211)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.internal.btree.FreeListBlockStore$FreeListBlock.alloc(FreeListBlockStore.java:221)
	at org.gradle.cache.inter<message truncated>

--- details for Resolution failed
Resolution failed

Failed to fetch the following dependencies:
com.google.firebase:firebase-analytics:18.0.3
com.google.firebase:firebase-analytics-unity:7.2.0
com.google.firebase:firebase-common:19.5.0
com.google.android.gms:play-services-base:17.6.0
com.google.firebase:firebase-app-unity:7.2.0

UnityEngine.Debug:LogError (object)
Google.Logger:Log (string,Google.LogLevel) (at Z:/tmp/tmp.PCm8n7eeW2/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:136)
GooglePlayServices.PlayServicesResolver:Log (string,Google.LogLevel) (at Z:/tmp/tmp.pQEak8lcmj/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/PlayServicesResolver.cs:1055)
GooglePlayServices.GradleResolver:LogMissingDependenciesError (System.Collections.Generic.List`1<string>) (at Z:/tmp/tmp.pQEak8lcmj/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:95)
GooglePlayServices.GradleResolver/<DoResolutionUnsafe>c__AnonStorey8:<>m__1 (System.Collections.Generic.List`1<Google.JarResolver.Dependency>) (at Z:/tmp/tmp.pQEak8lcmj/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:912)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey1:<>m__0 () (at Z:/tmp/tmp.pQEak8lcmj/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:375)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey1:<>m__2 (GooglePlayServices.CommandLine/Result) (at Z:/tmp/tmp.pQEak8lcmj/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:454)
GooglePlayServices.GradleResolver/<GradleResolution>c__AnonStorey1/<GradleResolution>c__AnonStorey3:<>m__0 () (at Z:/tmp/tmp.pQEak8lcmj/third_party/unity/unity_jar_resolver/source/AndroidResolver/src/GradleResolver.cs:564)
Google.RunOnMainThread:ExecuteNext () (at Z:/tmp/tmp.PCm8n7eeW2/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:486)
Google.RunOnMainThread:<ExecuteAllUnnested>m__1 () (at Z:/tmp/tmp.PCm8n7eeW2/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:536)
Google.RunOnMainThread:RunAction (System.Action) (at Z:/tmp/tmp.PCm8n7eeW2/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:343)
Google.RunOnMainThread:ExecuteAllUnnested (bool) (at Z:/tmp/tmp.PCm8n7eeW2/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:530)
Google.RunOnMainThread:ExecuteAll () (at Z:/tmp/tmp.PCm8n7eeW2/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:512)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /Users/bokken/buildslave/unity/build/Editor/Mono/EditorApplication.cs:327)

**Comment by paulinon** [comment]
Hi @martymayfly,

It appears that this issue is more related to the [External Dependency Manager](https://github.com/googlesamples/unity-jar-resolver/issues). You can file a ticket there so that your issue could be handled appropriately.

With that, I'll be closing this ticket for now.
