### ISSUE TITLE
[Bug] Firestore crash when using Android emulator

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#1065]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.9f1
  * Firebase Unity SDK version: 7.2.0
  * Source you installed the SDK: Unity Package Manager with tgz
  * Problematic Firebase Component: Firestore
  * Other Firebase Components in use: Auth, Crashlytics, Remote Config
  * Additional SDKs you are using: 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

```
E/AndroidRuntime( 5020): FATAL EXCEPTION: main
E/AndroidRuntime( 5020): Process: com.example.game, PID: 5020
E/AndroidRuntime( 5020): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime( 5020): Unity version     : 2020.3.9f1
E/AndroidRuntime( 5020): Device model      : samsung SM-G955N
E/AndroidRuntime( 5020): Device fingerprint: samsung/SM-G955N/dream2lteks:5.1.1/NRD90M/500200305:user/release-keys
E/AndroidRuntime( 5020): Build Type        : Release
E/AndroidRuntime( 5020): Scripting Backend : IL2CPP
E/AndroidRuntime( 5020): ABI               : armeabi-v7a
E/AndroidRuntime( 5020): Strip Engine Code : true

E/AndroidRuntime( 5020): Caused by: java.lang.RuntimeException: Internal error in Cloud Firestore (22.1.2).

E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:534)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(AsyncQueue.java)
E/AndroidRuntime( 5020): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 5020): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5020): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5020): 	at android.app.ActivityThread.main(ActivityThread.java:5307)
E/AndroidRuntime( 5020): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5020): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5020): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 5020): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 5020): Caused by: java.lang.IllegalArgumentException: Timestamp seconds out of range: 6967862201976803777
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.util.Preconditions.checkArgument(Preconditions.java:117)
E/AndroidRuntime( 5020): 	at com.google.firebase.Timestamp.validateRange(Timestamp.java:159)
E/AndroidRuntime( 5020): 	at com.google.firebase.Timestamp.<init>(Timestamp.java:63)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.RemoteSerializer.decodeTimestamp(RemoteSerializer.java:110)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.RemoteSerializer.decodeVersion(RemoteSerializer.java:121)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.RemoteSerializer.decodeWatchChange(RemoteSerializer.java:873)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:106)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:38)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onNext$1(AbstractStream.java:119)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$Lambda$2.run(AbstractStream.java)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onNext(AbstractStream.java:110)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.remote.FirestoreChannel$1.onMessage(FirestoreChannel.java:125)
E/AndroidRuntime( 5020): 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:658)
E/AndroidRuntime( 5020): 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:643)
E/AndroidRuntime( 5020): 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
E/AndroidRuntime( 5020): 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
E/AndroidRuntime( 5020): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
E/AndroidRuntime( 5020): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime( 5020): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
E/AndroidRuntime( 5020): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
E/AndroidRuntime( 5020): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 5020): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 5020): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:229)
E/AndroidRuntime( 5020): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager( 1779):   Force finishing activity 1 com.example.game/com.google.firebase.MessagingUnityPlayerActivity
```

**Comment by paulinon** [comment]
Hi @Nyankoo,

In order to identify what's causing this behavior, could you share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project along with the steps you've taken before facing this issue?

**Comment by schmidt-sebastian** [comment]
Furthermore, are you able to share debug logs if this is reproducible? You can change the log level with this API: https://firebase.google.com/docs/reference/unity/namespace/firebase#namespace_firebase_1ae165d1d7bc3d85e1c0463a2a1d9ced9a

If you change the log level to DEBUG then will be able to see the messages that the SDK receives from the backend.

**Comment by Nyankoo** [comment]
@schmidt-sebastian I'm still trying to recreate this in a minimal repro, but in the meantime, you can find the complete logcat with DEBUG enabled here.

[62001_logcat.txt](https://github.com/firebase/quickstart-unity/files/6594628/62001_logcat.txt)

**Comment by schmidt-sebastian** [comment]
Unfortunately, Firestore only logs its network traffic when the log level is explicitly set to debug. Even if you cannot create a minimal repro, a debug log that shows the network traffic would help tremendously.

**Comment by Nyankoo** [comment]
@schmidt-sebastian The log level is set to debug in the above logcat file (with `FirebaseApp.LogLevel = LogLevel.Debug`)

**Comment by schmidt-sebastian** [comment]
The log level for Firestore is independent from FirebaseApp. You should see some log messages that show the communication from the WatchStream and the WriteStream.

**Comment by Nyankoo** [comment]
@schmidt-sebastian Any guides or pointers how to correctly set this up so I can provide a useful logcat?

**Comment by var-const** [comment]
You can use
```csharp
FirebaseFirestore.LogLevel = LogLevel.Debug;
```

**Comment by Nyankoo** [comment]
@var-const Thank you!

@schmidt-sebastian Please find the logcat with WatchStream and WriteStream below.
[62001_logcat.txt](https://github.com/firebase/quickstart-unity/files/6602252/62001_logcat.txt)

**Comment by schmidt-sebastian** [comment]
@Nyankoo Are you talking to our production backend or to the Emulator?

**Comment by Nyankoo** [comment]
@schmidt-sebastian What exactly do you mean?

**Comment by schmidt-sebastian** [comment]
Are you using "useEmulator()" in your app and talking to "localhost" instead of "firestore.googleapis.com"?

**Comment by Nyankoo** [comment]
@schmidt-sebastian I'm not using any special emulator-related methods.

**Comment by Nyankoo** [comment]
We also just had a crash report through Crashlytics on a Reno Ace with Android 5.1.1, but we can't confirm if this is actually an emulator or real device on the user's end.

**Comment by Nyankoo** [comment]
@schmidt-sebastian Any progress with this issue?

**Comment by schmidt-sebastian** [comment]
We believe this is invalid data coming from the backend. We have a bug to track this - b/191139962. There are no updates yet.

**Comment by potatoyz** [comment]
Hello, has this bug been fixed?
