### ISSUE TITLE
Dynamic Link crashes app

### ISSUE THREAD

**Issue by comtaler** [firebase/quickstart-unity#11]
I created a dynamic link on the firebase console with Link name and Link URL set. With the dynamic link generated, I created webpage with this link and click on the link. After it launches the app, the app crashes (Running the test app to send invites to email and click the link in the email works fine).

Here is the entire logcat output:

```
D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
D/FirebaseApp: com.google.firebase.iid.FirebaseInstanceId is not linked. Skipping initialization.
D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
D/FirebaseApp: com.google.android.gms.measurement.AppMeasurement is not linked. Skipping initialization.
I/FirebaseInitProvider: FirebaseApp initialization successful
V/Monotype: SetAppTypeFace- try to flip, app = com.google.firebase.unity.invites.testapp
V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
V/Monotype: SetAppTypeFace- try to flip, app = com.google.firebase.unity.invites.testapp
V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
I/Unity: splash_mode = 0 (integer)
I/Unity: useObb = False (bool)
I/Unity: onResume
D/Unity: [EGL] Attaching window :0xee951208
D/Unity: [EGL] Attaching window :0xee951208
I/Unity: windowFocusChanged: true
D/Unity: SystemInfo CPU = Intel x86 SSE3, Cores = 4, Memory = 3907mb
D/Unity: [SHA1] eedb14ec49d7f6b138ce3383e96afc53fd010c06   26157092 bytes ~ lib/armeabi-v7a/libunity.so
D/Unity: [SHA1] af4a5515324d20da8654a1e9248fd4218c0eefa1      25316 bytes ~ lib/armeabi-v7a/libmain.so
D/Unity: [SHA1] cf79e315d87e48141978629baa759ccadc0bb137    3762548 bytes ~ lib/armeabi-v7a/libmono.so
D/Unity: [SHA1] b2ac7c29110405829ce1563704cc29a74c6815c1   29887148 bytes ~ lib/x86/libunity.so
D/Unity: [SHA1] 6bc471c370e126c553ccad215df4ff2a63981624       8120 bytes ~ lib/x86/libmain.so
D/Unity: [SHA1] 899983818efd6b1863f4a0ee48347f8400837000    3628252 bytes ~ lib/x86/libmono.so
D/Unity: Mono path[0] = '/data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed'
D/Unity: Mono config path = 'assets/bin/Data/Managed'
D/Unity: PlayerConnection initialized from /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data (debug = 0)
D/Unity: PlayerConnection initialized network socket : 0.0.0.0 55318
D/Unity: PlayerConnection initialized unix socket : Unity-com.google.firebase.unity.invites.testapp
D/Unity: Multi-casting "[IP] 192.168.3.23 [Port] 55318 [Flags] 2 [Guid] 4176766349 [EditorId] 3770221696 [Version] 1048832 [Id] AndroidPlayer(asus_ASUS_Z00AD@192.168.3.23) [Debug] 0" to [225.0.0.222:54997]...
D/Unity: InitializeScriptEngine OK (000d8ee0)
D/Unity: PlayerConnection already initialized - listening to [192.168.3.23:55318]
D/Unity: PlayerInitEngineNoGraphics OK
D/Unity: [EGL] Request: ES 3.1+AEP RGB0 000 0/0
D/Unity: [EGL] Checking ES 3.1 support...
D/Unity: [EGL] ES 3.1 support detected
D/Unity: [EGL] Found: ID[25] ES 3.1+AEP RGB16 565 0/0
D/Unity: [EGL] Request: ES 3.1+AEP RGB0 000 0/0
D/Unity: [EGL] Found: ID[25] ES 3.1+AEP RGB16 565 0/0
D/Unity: [EGL] Request: ES 3.0 RGBA32 8888 0/0
D/Unity: [EGL] Found: ID[15] ES 3.0 RGBA32 8888 0/0 AFBT
D/Unity: ANativeWindow: (1080/1920) RequestedResolution: (0/0) EGLSurface: (1080/1920)
D/Unity: Renderer: PowerVR Rogue G6430
D/Unity: Vendor:   Imagination Technologies
D/Unity: Version:  OpenGL ES 3.1 build 1.4@3283119
D/Unity: GLES:     3
D/Unity:  GL_EXT_blend_minmax GL_EXT_color_buffer_float GL_EXT_discard_framebuffer GL_EXT_draw_buffers GL_EXT_multi_draw_arrays GL_EXT_multisampled_render_to_texture GL_EXT_occlusion_query_boolean GL_EXT_read_format_bgra GL_EXT_robustness GL_EXT_separate_shader_objects GL_EXT_shader_framebuffer_fetch GL_EXT_shader_texture_lod GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_rg GL_EXT_texture_sRGB_decode GL_IMG_multisampled_render_to_texture GL_IMG_program_binary GL_IMG_read_format GL_IMG_shader_binary GL_IMG_texture_compression_pvrtc GL_IMG_texture_compression_pvrtc2 GL_IMG_texture_format_BGRA8888 GL_IMG_texture_npot GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_debug GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_depth_texture GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_element_index_uint GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_mapbuffer GL_OES_packed_depth_stencil GL_OES_required_internalformat GL
D/Unity: _OES_rgb8_rgba8 GL_OES_shader_image_atomic GL_OES_standard_derivatives GL_OES_surfaceless_context GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_npot GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_OES_vertex_array_object GL_OES_vertex_half_float
W/ContextImpl: Failed to ensure directory: /storage/MicroSD/Android/data/com.google.firebase.unity.invites.testapp/cache
D/Unity: OPENGL LOG: Creating OpenGL ES 3.1 graphics device ; Context level  <OpenGL ES 3.1 AEP> ; Context handle -566240672
D/Unity: InitializeGfxDevice OK
D/Unity: Initialize engine version: 5.4.2f2 (b7e030c65c9b)
D/Unity: AudioManager: Selecting AudioTrack output...
W/libc: pthread_create sched_setscheduler call failed: Operation not permitted
D/Unity: Begin MonoManager ReloadAssembly
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/UnityEngine.dll (this message is harmless)
D/Unity: Loading /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/UnityEngine.dll into Unity Child Domain
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Assembly-CSharp.dll (this message is harmless)
D/Unity: Loading /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Assembly-CSharp.dll into Unity Child Domain
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/UnityEngine.UI.dll (this message is harmless)
D/Unity: Loading /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/UnityEngine.UI.dll into Unity Child Domain
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/UnityEngine.Networking.dll (this message is harmless)
D/Unity: Loading /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/UnityEngine.Networking.dll into Unity Child Domain
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Firebase.App.dll (this message is harmless)
D/Unity: Loading /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Firebase.App.dll into Unity Child Domain
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Firebase.Invites.dll (this message is harmless)
D/Unity: Loading /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Firebase.Invites.dll into Unity Child Domain
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Unity.Compat.dll (this message is harmless)
D/Unity: Loading /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Unity.Compat.dll into Unity Child Domain
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Unity.Tasks.dll (this message is harmless)
D/Unity: Loading /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/Unity.Tasks.dll into Unity Child Domain
D/Unity: - Completed reload, in  0.090 seconds
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/System.Core.dll (this message is harmless)
D/Unity: Platform assembly: /data/app/com.google.firebase.unity.invites.testapp-2/base.apk/assets/bin/Data/Managed/System.dll (this message is harmless)
D/Unity: PlayerInitEngineGraphics OK
D/Unity: Found 25 native sensors
D/Unity: Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; PSH Accelerometer / Intel Inc. 
D/Unity: Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; PSH Accelerometer / Intel Inc. 
D/Unity: Requested framebuffer: resolution[1080x1920], rgba[8/8/8/8], depth+stencil[on], samples[1]
D/Unity: Created framebuffer: resolution[1080x1920], rgba[8/8/8/8], depth+stencil[24/8], samples[0] 
D/Unity: UnloadTime: 2.162000 ms
D/Unity: Sensor :        Accelerometer ( 1) ; 0.009577 / 0.01s ; PSH Accelerometer / Intel Inc. 
D/Unity: Choreographer available: Enabling VSYNC timing
I/firebase: firebase::App initializing app com.google.firebase.unity.invites.testapp (default 1).
D/Unity: firebase::App initializing app com.google.firebase.unity.invites.testapp (default 1).: 0 at ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp:42 (17408, 0, 0)
I/Unity: firebase::App initializing app com.google.firebase.unity.invites.testapp (default 1).
         UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
         UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
         UnityEngine.Logger:Log(LogType, Object)
         UnityEngine.Debug:Log(Object)
         Firebase.FirebaseHandler:LogMessage(LogLevel, String)
         Firebase.AppUtilPINVOKE:FirebaseApp_CreateInternal__SWIG_0()
         Firebase.FirebaseApp:CreateInternal()
         Firebase.FirebaseApp:<Create>m__1()
         Firebase.FirebaseApp:CreateAndTrack(CreateDelegate)
         Firebase.FirebaseApp:Create()
         Firebase.FirebaseApp:get_DefaultInstance()
         Firebase.FirebaseApp:CheckDependencies()
         UIHandler:Start() (at E:\airgc3\unity\quickstart-unity\invites\testapp\Assets\TestApp\UIHandler.cs:37)
          
         (Filename: E Line: 0)
D/Unity: Setting up firebase...: 0 at ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp:42 (17408, 0, 0)
I/Unity: Setting up firebase...
         UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
         UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
         UnityEngine.Logger:Log(LogType, Object)
         UnityEngine.Debug:Log(Object)
         UnityEngine.MonoBehaviour:print(Object) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs:107)
         UIHandler:DebugLog(String) (at E:\airgc3\unity\quickstart-unity\invites\testapp\Assets\TestApp\UIHandler.cs:137)
         UIHandler:InitializeFirebase() (at E:\airgc3\unity\quickstart-unity\invites\testapp\Assets\TestApp\UIHandler.cs:57)
         UIHandler:Start() (at E:\airgc3\unity\quickstart-unity\invites\testapp\Assets\TestApp\UIHandler.cs:51)
          
         (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs Line: 107)
D/Unity: Invites initialized: 0 at ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp:42 (17408, 0, 0)
I/Unity: Invites initialized
         UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
         UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
         UnityEngine.Logger:Log(LogType, Object)
         UnityEngine.Debug:Log(Object)
         UnityEngine.MonoBehaviour:print(Object) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs:107)
         UIHandler:DebugLog(String) (at E:\airgc3\unity\quickstart-unity\invites\testapp\Assets\TestApp\UIHandler.cs:137)
         UIHandler:InitializeFirebase() (at E:\airgc3\unity\quickstart-unity\invites\testapp\Assets\TestApp\UIHandler.cs:61)
         UIHandler:Start() (at E:\airgc3\unity\quickstart-unity\invites\testapp\Assets\TestApp\UIHandler.cs:51)
          
         (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineMonoBehaviourBindings.gen.cs Line: 107)
D/firebase_log: Creating Log instance.
D/firebase: (firebase_log) class com.google.firebase.app.internal.cpp.Log
D/Unity: (firebase_log) class com.google.firebase.app.internal.cpp.Log: 0 at ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp:42 (17408, 0, 0)
I/Unity: (firebase_log) class com.google.firebase.app.internal.cpp.Log
         UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
         UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
         UnityEngine.Logger:Log(LogType, Object)
         UnityEngine.Debug:Log(Object)
         Firebase.FirebaseHandler:LogMessage(LogLevel, String)
          
         (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
D/firebase: (InvitesClass) getInvitation:onResult:Status{statusCode=SUCCESS, resolution=null}
D/Unity: (InvitesClass) getInvitation:onResult:Status{statusCode=SUCCESS, resolution=null}: 0 at ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp:42 (17408, 0, 0)
I/Unity: (InvitesClass) getInvitation:onResult:Status{statusCode=SUCCESS, resolution=null}
         UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
         UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
         UnityEngine.Logger:Log(LogType, Object)
         UnityEngine.Debug:Log(Object)
         Firebase.FirebaseHandler:LogMessage(LogLevel, String)
          
         (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
         
         
         
         --------- beginning of crash
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 19749 (invites.testapp)
```

**Comment by stewartmiles** [comment]
Any chance you could share the rest of the crash log?  Looks like the logcat output is cut off after "-- beginning of crash".

**Comment by comtaler** [comment]
I copied all the logs filtered by the application name. I have removed the filter and here is the rest of the log:

```
11-22 10:37:23.313 1385-1385/com.google.firebase.unity.invites.testapp A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 1385 (invites.testapp)
11-22 10:37:23.414 21074-21074/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-22 10:37:23.414 21074-21074/? I/DEBUG: Build fingerprint: 'asus/WW_Z00A/Z00A:5.0/LRX21V/2.20.40.184_20160504_4658_user:user/release-keys'
11-22 10:37:23.414 21074-21074/? I/DEBUG: Revision: '0'
11-22 10:37:23.414 21074-21074/? I/DEBUG: ABI: 'x86'
11-22 10:37:23.414 21074-21074/? I/DEBUG: pid: 1385, tid: 1385, name: invites.testapp  >>> com.google.firebase.unity.invites.testapp <<<
11-22 10:37:23.415 21074-21074/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
11-22 10:37:23.423 21074-21074/? I/DEBUG:     eax 00000000  ebx db7f8e84  ecx ffffffff  edx 00000000
11-22 10:37:23.424 21074-21074/? I/DEBUG:     esi eb210f10  edi 00000000
11-22 10:37:23.424 21074-21074/? I/DEBUG:     xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000007  xss 0000002b
11-22 10:37:23.424 21074-21074/? I/DEBUG:     eip db75c34f  ebp eb210f14  esp ffac5760  flags 00210246
11-22 10:37:23.424 21074-21074/? I/DEBUG: backtrace:
11-22 10:37:23.424 21074-21074/? I/DEBUG:     #00 pc 0004434f  /data/app/com.google.firebase.unity.invites.testapp-2/lib/x86/libApp.so (_ZN8firebase7invites12ListenerImpl16OnInviteReceivedEPKcS3_b+83)
11-22 10:37:23.424 21074-21074/? I/DEBUG:     #01 pc 00044f1a  /data/app/com.google.firebase.unity.invites.testapp-2/lib/x86/libApp.so (_ZN8firebase7invites26SendCachedInviteToListenerEv+225)
11-22 10:37:23.424 21074-21074/? I/DEBUG:     #02 pc 000451fa  /data/app/com.google.firebase.unity.invites.testapp-2/lib/x86/libApp.so (_ZN8firebase7invites20HandleReceivedInviteERKNS0_14ReceivedInviteE+174)
11-22 10:37:23.424 21074-21074/? I/DEBUG:     #03 pc 000454f0  /data/app/com.google.firebase.unity.invites.testapp-2/lib/x86/libApp.so (_ZN8firebase7invites8internal23InvitesReceiverInternal22ReceivedInviteCallbackERKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEESB_biS9_+122)
11-22 10:37:23.424 21074-21074/? I/DEBUG:     #04 pc 000468af  /data/app/com.google.firebase.unity.invites.testapp-2/lib/x86/libApp.so (Java_com_google_firebase_invites_internal_cpp_AppInviteNativeWrapper_receivedInviteCallback+419)
11-22 10:37:23.424 21074-21074/? I/DEBUG:     #05 pc 0000247e  /data/data/com.google.firebase.unity.invites.testapp/code_cache/invites_resources_lib.dex
11-22 10:37:23.410 21074-21074/? W/debuggerd: type=1400 audit(0.0:1276): avc: denied { search } for name="com.google.firebase.unity.invites.testapp" dev="mmcblk0p19" ino=3490526 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0 tclass=dir result=0
11-22 10:37:23.410 21074-21074/? W/debuggerd: type=1400 audit(0.0:1277): avc: denied { search } for name="com.google.firebase.unity.invites.testapp" dev="mmcblk0p19" ino=3490526 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0 tclass=dir result=0
11-22 10:37:23.777 632-662/? D/BrightnessHandler: IBrightnesssListener: onBrightnessChnaged: 48, policy: 3, auto: true
11-22 10:37:23.777 632-771/? E/lights: [BL] mode=0  brightness=48
11-22 10:37:23.806 632-1601/? W/ActivityManager:   Force finishing activity com.google.firebase.unity.invites.testapp/com.unity3d.player.UnityPlayerActivity
11-22 10:37:23.806 21074-21074/? I/DEBUG: Tombstone written to: /data/tombstones/tombstone_04
11-22 10:37:23.807 632-656/? I/BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
11-22 10:37:23.807 632-2165/? E/SharedPreferencesImpl: Couldn't create directory for SharedPreferences file shared_prefs/log_files.xml
11-22 10:37:23.842 632-1601/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
11-22 10:37:23.843 632-1601/? W/ActivityManager: Exception thrown during pause
                                                 android.os.TransactionTooLargeException
                                                     at android.os.BinderProxy.transactNative(Native Method)
                                                     at android.os.BinderProxy.transact(Binder.java:496)
                                                     at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:701)
                                                     at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:852)
                                                     at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2782)
                                                     at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2639)
                                                     at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2534)
                                                     at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11689)
                                                     at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11586)
                                                     at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12265)
                                                     at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11781)
                                                     at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
11-22 10:37:23.845 241-241/? E/lowmemorykiller: Error writing /proc/1385/oom_score_adj; errno=22
11-22 10:37:23.847 632-1601/? D/WindowManager: adjustConfigurationLw, config:{0 1.0 ?mcc?mnc ?locale ?layoutDir sw360dp w360dp h615dp 480dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:true config.hardKeyboardHidden:2
11-22 10:37:23.849 813-9205/? D/KeyguardViewMediator: setOccluded false
11-22 10:37:23.850 813-813/? D/StatusBarKeyguardViewManager: reset(), mShowing = false
11-22 10:37:23.850 813-813/? D/StatusBarKeyguardViewManager: inflateKeyguardView...
11-22 10:37:23.853 632-1601/? W/ActivityManager:   Force finishing activity com.android.chrome/org.chromium.chrome.browser.ChromeTabbedActivity
11-22 10:37:23.854 632-660/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
11-22 10:37:23.855 632-1601/? E/ActivityManager: Invalid thumbnail dimensions: 576x576
11-22 10:37:23.856 813-813/? D/KeyguardViewMediator: adjustStatusBarLocked: mShowing=false mOccluded=false isSecure=true --> flags=0x0
11-22 10:37:23.857 1707-1722/? D/ForegroundUtils: Foreground changed, PID: 30174 UID: 10075 foreground: true
11-22 10:37:23.857 1707-1722/? D/ForegroundUtils: Foreground UID/PID combinations:
11-22 10:37:23.857 1707-1722/? D/ForegroundUtils: UID: 10075 PID: 30174
11-22 10:37:23.858 1707-1722/? D/ForegroundUtils: UID: 10283 PID: 1385
11-22 10:37:23.870 632-1246/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
11-22 10:37:23.870 3650-3650/? I/MoviePlayerForL: MoviePlayerForL onSystemUiVisibilityChange, mIsPlayComplete is false and call mController.show()
11-22 10:37:23.882 632-1231/? D/ConnectivityService: listenForNetwork for NetworkRequest [ id=1396, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
11-22 10:37:23.883 632-756/? D/ConnectivityService: handleRegisterNetworkRequest checking NetworkAgentInfo [WIFI () - 273]
11-22 10:37:23.883 632-756/? D/ConnectivityService: apparently satisfied.  currentScore=60
11-22 10:37:23.885 30174-30406/? D/ConnectivityManager.CallbackHandler: CM callback handler got msg 524290
11-22 10:37:23.889 632-1231/? W/MediaFocusControl:   AudioFocus   audio focus client died
11-22 10:37:23.889 632-1231/? I/MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@18dac39d
11-22 10:37:23.890 315-315/? I/Zygote: Process 1385 exited due to signal (11)
11-22 10:37:23.892 632-1231/? I/ActivityManager: Process com.google.firebase.unity.invites.testapp (pid 1385) has died
11-22 10:37:23.896 632-745/? W/InputDispatcher: channel '2b555330 com.google.firebase.unity.invites.testapp/com.unity3d.player.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-22 10:37:23.896 632-745/? E/InputDispatcher: channel '2b555330 com.google.firebase.unity.invites.testapp/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

```

**Comment by stewartmiles** [comment]
The stack is *extremely useful* thank you!

We found the bug in our C++ --> C# layer.  The C++ API is reporting a nullptr for the invitation ID which isn't being handled by the listener implementation in the C# interface.  So basically right now things are going to crash if the link doesn't have an invitation ID set.

**Comment by comtaler** [comment]
Do you have a rough estimate on when the fix will be released? Our app is going beta on January. Will the fix made it before that? Thanks!

**Comment by stewartmiles** [comment]
Yep, we should have a fix available within the next couple of weeks.

Cheers,
Stewart

**Comment by stewartmiles** [comment]
I'm pleased to announce that we released:

- Firebase C++ SDK 2.1.0 (release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#2.1.0), download [here](https://firebase.google.com/docs/cpp/setup))
- Firebase Unity SDK 1.1.0 (release notes [here](https://firebase.google.com/support/release-notes/unity#1.1.0), download [here](https://firebase.google.com/docs/unity/setup))

I believe this should resolve your issue.  If not, please let us know and we'll take a look.

Cheers,
Stewart
