### ISSUE TITLE
Uncaught exception in Firebase Database runloop (20.0.0)

### ISSUE THREAD

**Issue by AjayC-Bsw** [firebase/quickstart-unity#1190]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.30f1
  * Firebase Unity SDK version: 8.6.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Database
  * Other Firebase Components in use: _____ (Auth, Database, Fcm, Analytics, Function)
  * Additional SDKs you are using: (Facebook, AdMob)
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP
  * Strip Engine Code :  Checked
  *  Pro-guard : NO

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? NO
What's the issue repro rate? .02% user impacted

What happened? How can we make the problem occur? Unable to repro

#### Logs:

```
Caused by java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.0). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:96)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

```
Caused by java.lang.AssertionError: hardAssert failed: Expected connection state disconnected, but was GettingToken
       at com.google.firebase.database.connection.ConnectionUtils.hardAssert(ConnectionUtils.java:67)
       at com.google.firebase.database.connection.PersistentConnectionImpl.lambda$tryScheduleReconnect$0$PersistentConnectionImpl(PersistentConnectionImpl.java:766)
       at com.google.firebase.database.connection.-$$Lambda$PersistentConnectionImpl$68je9bMWK83IDxcYAZ2qYbVbJFk.onSuccess(:11)
       at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)```

**Comment by paulinon** [comment]
Hi @AjayC-Bsw,

Thanks for reporting this. It seems that this is related to this [issue](https://github.com/firebase/firebase-android-sdk/issues/3074) with the Android SDK. The team is currently working on this. 

I'll be marking this as a bug for now. We'll let you know once we have updates.
