### ISSUE TITLE
Firebase_Auth_CSharp_UserInfoInterface_ProviderId_get line 28

### ISSUE THREAD

**Issue by Originator99** [firebase/quickstart-unity#1207]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.21f1
  * Firebase Unity SDK version: 8.6.2
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Auth 
  * Other Firebase Components in use: Database, Analytics, Messaging, Crashlytics, Dynamic Links, Installations
  * Additional SDKs you are using: Ironsource (Facebook, Admob, 
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android & iOS
  * Scripting Runtime: il2cpp

### [REQUIRED] Please describe the issue here:

We did not change anything related to Auth. The crash started happening out of nowhere. After firebase token is fetched, we get the provider ID as a string. Fetching of provider ID does not happen if this process is faulted or canceled. Here is the stack trace of the crash recorded : 

at libFirebaseCppApp-8_6_2.Firebase_Auth_CSharp_UserInfoInterface_ProviderId_get(Firebase_Auth_CSharp_UserInfoInterface_ProviderId_get:28)
       at libil2cpp.0x1d0087c()
       at libil2cpp.0x1d05da8()
       at libil2cpp.0xd6e8ac()
       at libil2cpp.0xd6e328()
       at libil2cpp.0x21df624()
       at libil2cpp.0x1613350()
       at libil2cpp.0xf807f0()
       at libil2cpp.0x19826f4()
       at libil2cpp.0x1613a80()
       at libil2cpp.0x1613884()
       at libil2cpp.0x1595020()
       at libil2cpp.0x98b098()
       at libil2cpp.0x8e93a8()
       at libil2cpp.0x8b2838()
       at libil2cpp.0x87ea94()
       at libil2cpp.0x87d418()
       at libc.__pthread_start(void*)(__pthread_start:64)
       at libc.__start_thread(__start_thread:64)

This crash was also noticed in firebase version 8.6.1. I was not able to reproduce this crash. We've recorded in total of 100 instances of this crash since 2 weeks.

**Comment by paulinon** [comment]
Hi @Originator99,

Thanks for reporting this. In order to identify what's causing this behavior, could you verify if this issue persists using the [quickstart](https://github.com/firebase/quickstart-unity/tree/master/auth/testapp)? If so, please provide the complete steps to reproduce the issue.

**Comment by Originator99** [comment]
> 

Hi @paulinon , thank you for the quick response. 
I was not able to re-produce this using quickstart.

**Comment by paulinon** [comment]
Hi @Originator99,

[Version 8.7.0](https://firebase.google.com/support/release-notes/unity#version_870_-_december_15_2021) of the SDK has been released recently. Could you try this out and see if it resolves the issue? If it doesn't, kindly provide a sample code that I could try on my end along with the complete steps to replicate this issue.

**Comment by Originator99** [comment]
> Hi @Originator99,
> 
> [Version 8.7.0](https://firebase.google.com/support/release-notes/unity#version_870_-_december_15_2021) of the SDK has been released recently. Could you try this out and see if it resolves the issue? If it doesn't, kindly provide a sample code that I could try on my end along with the complete steps to replicate this issue.

Hi ,
I'll do the upgrade and get back to you with results in 1.5-2 weeks at Max. 

Thank you

**Comment by Originator99** [comment]
Hi @paulinon 
Thank you for your patience. 
We had made a release 2 days ago with firebase upgraded to version 8.7.0.
Unfortunately, the crash seems to be happening in this version too.  However there was a new crash trace that was logged. 

```
backtrace:
  at __memcpy
  at std::__ndk1::vector<firebase::auth::UserInfoInterface*, std::__ndk1::allocator<firebase::auth::UserInfoInterface*> >::__swap_out_circular_buffer(std::__ndk1::__split_buffer<firebase::auth::UserInfoInterface*, std::__ndk1::allocator<firebase::auth::UserInfoInterface*>&>&)
  at std::__ndk1::vector<firebase::auth::UserInfoInterface*, std::__ndk1::allocator<firebase::auth::UserInfoInterface*> >::__append(unsigned long)
  at firebase::auth::User::provider_data() const
  at Firebase_Auth_CSharp_FirebaseUser_ProviderData_get
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at 
  at __pthread_start(void*)
  at __start_thread
  at libc.__memcpy
  at libFirebaseCppApp
  at libFirebaseCppApp-8_7_0.std::__ndk1::vector<firebase::auth::UserInfoInterface*, std::__ndk1::allocator<firebase::auth::UserInfoInterface*> >::__append (unsigned long)(__append:152)
  at libFirebaseCppApp-8_7_0.firebase::auth::User::provider_data () const(provider_data:112)
  at libFirebaseCppApp-8_7_0.Firebase_Auth_CSharp_FirebaseUser_ProviderData_get (Firebase_Auth_CSharp_FirebaseUser_ProviderData_get:8)
  at libil2cpp.0x1db3f58 (Native Method)
  at libil2cpp.0x1db7344 (Native Method)
  at libil2cpp.0xc8afac (Native Method)
  at libil2cpp.0xc8ac50 (Native Method)
  at libil2cpp.0x21fa0c8 (Native Method)
  at libil2cpp.0x167cc70 (Native Method)
  at libil2cpp.0x1052724 (Native Method)
  at libil2cpp.0x1a4c358 (Native Method)
  at libil2cpp.0x167d3a0 (Native Method)
  at libil2cpp.0x167d1a4 (Native Method)
  at libil2cpp.0x15fb940 (Native Method)
  at libil2cpp.0x9c4bdc (Native Method)
  at libil2cpp.0x922bd8 (Native Method)
  at libil2cpp.0x8ec068 (Native Method)
  at libil2cpp.0x8b82c4 (Native Method)
  at libil2cpp.0x8b6c48 (Native Method)
  at libc.__pthread_start
  at libc.__start_thread (__start_thread:64)
```

**Comment by Originator99** [comment]
Hi , thought I'd drop an update with a comment of the code snippet where the crash seems to be happening in our game. I am also including a better stack trace of the crash recorded. 

```
public void UpdateAuthProvidersData() {
        Firebase.Auth.FirebaseUser user = auth.CurrentUser;
        Debug.Log(user);
        if(user != null) {
            IEnumerable<Firebase.Auth.IUserInfo> user_profiles = user.ProviderData; //at this line where crash seems to be happening
            foreach(Firebase.Auth.IUserInfo info in user_profiles) {
                if(info.ProviderId == "facebook.com") {
                    isFacebookConnected = true;
                }
                if(info.ProviderId == "playgames.google.com") {
                    isGooglePlayConnected = true;

                }

                if(info.ProviderId == "apple.com") {
                    isAppleConnected = true;
                }
                Debug.Log($"{info.ProviderId} is linked");
            }
        } else {
            Debug.LogError("Firebase User is null");
        }
    }
```

I have marked the line where the crash seems to be happening According to this stack trace : 
```

Thread 0 (crashed)
0   libc.so                            0x000000764adbe808 <symbols missing for uuid: 554cb674fad07588ff08040bb89924c9> 
1   libFirebaseCppApp-8_7_0.so         0x00000073a7b89a68 <symbols missing for uuid: 3104bb0105330426b5c947b4131b049c> 
2   libFirebaseCppApp-8_7_0.so         0x00000073a7b94dfc <symbols missing for uuid: 3104bb0105330426b5c947b4131b049c> 
3   libFirebaseCppApp-8_7_0.so         0x00000073a7b93f84 <symbols missing for uuid: 3104bb0105330426b5c947b4131b049c> 
4   libFirebaseCppApp-8_7_0.so         0x00000073a7b86a0c <symbols missing for uuid: 3104bb0105330426b5c947b4131b049c> 
5   libil2cpp.so                       0x0000007537a01f58 AuthUtilPINVOKE_FirebaseUser_ProviderData_get_m1B89485E8AF0AFEDFE4E34690516E15A9CFF79CE (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Firebase.Auth.cpp:6000)
6   libil2cpp.so                       0x0000007537a05344 FirebaseUser_get_ProviderData_mC41C8C4DC928DEA05201E099E541185693483607 (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Firebase.Auth.cpp:8829)
7   libil2cpp.so                       0x00000075368d8fac FirebaseLinkController_UpdateAuthProvidersData_m695238F4CA598C1016C49BC67F25628F3D6C3FB5 (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Assembly-CSharp11.cpp:50415)
8   libil2cpp.so                       0x00000075368d8c50 FirebaseLinkController_InitializeFirebaseExternal_m22159447855DF3975A95C956DF913528B793E75E (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Assembly-CSharp11.cpp:49381)
9   libil2cpp.so                       0x0000007537e480c8 Action_1_Invoke_m587509C88BB83721D7918D89DF07606BB752D744_gshared (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Generics1.cpp:0)
10  libil2cpp.so                       0x00000075372cac70 Task_Execute_m35673A0487248C5577449A4A3FBDF7FD3B6BA086 (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\mscorlib16.cpp:76)
11  libil2cpp.so                       0x0000007536ca0724 ContextCallback_Invoke_mF4F8496213E8F0925947DD8994A477AE2E54EFDF (C:\Program Files\Unity\Hub\Editor\2020.3.21f1\Editor\Data\il2cpp\libil2cpp\vm\ClassInlines.h:0)
12  libil2cpp.so                       0x000000753769a358 ExecutionContext_RunInternal_mC5D58D6EDE270B4CDA05181E9064E040D6692B2B (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\mscorlib6.cpp:27034)
13  libil2cpp.so                       0x00000075372cb3a0 Task_ExecuteWithThreadLocal_m25476BDF5AAFF102A95E92CB1E0989DFF72408A8 (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\mscorlib16.cpp:28867)
14  libil2cpp.so                       0x00000075372cb1a4 Task_ExecuteEntry_m55634616576BB085EF3CEDB04801C4183FE1B053 (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\mscorlib16.cpp:28731)
15  libil2cpp.so                       0x0000007537249940 ThreadPoolWorkQueue_Dispatch_mCC5743D99870EC7844CAB3FF3FA7D23A44A4A984 (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\mscorlib17.cpp:110)
16  libil2cpp.so                       0x0000007536612bdc RuntimeInvoker_FalseSByte_t928712DD662DC29BA4FAAE8CE2230AFB23447F0B(void (*)(), MethodInfo const*, void*, void**) (D:\HitwicketUnity2\Library\Il2cppBuildCache\Android\armeabi-v7a\il2cppOutput\Il2CppInvokerTable.cpp:110398)
17  libil2cpp.so                       0x0000007536570bd8 worker_thread(void*) (C:\Program Files\Unity\Hub\Editor\2020.3.21f1\Editor\Data\il2cpp\libil2cpp\mono\ThreadPool\ThreadPoolWorkerThread.cpp:250)
18  libil2cpp.so                       0x000000753653a068 il2cpp::vm::ThreadStart(void*) (C:\Program Files\Unity\Hub\Editor\2020.3.21f1\Editor\Data\il2cpp\libil2cpp\vm\Thread.cpp:708)
19  libil2cpp.so                       0x00000075365062c4 il2cpp::os::Thread::RunWrapper(void*) (C:\Program Files\Unity\Hub\Editor\2020.3.21f1\Editor\Data\il2cpp\libil2cpp\os\Thread.cpp:183)
20  libil2cpp.so                       0x0000007536504c48 il2cpp::os::ThreadImpl::ThreadStartWrapper(void*) (C:\Program Files\Unity\Hub\Editor\2020.3.21f1\Editor\Data\il2cpp\libil2cpp\os\Posix\ThreadImpl.cpp:125)
21  libc.so                            0x000000764ae25188 <symbols missing for uuid: 554cb674fad07588ff08040bb89924c9> 
22  libc.so                            0x000000764adc49d0 <symbols missing for uuid: 554cb674fad07588ff08040bb89924c9> 
```

**Comment by paulinon** [comment]
Thanks for the update, @Originator99. Could you provide a sample project that contains this function so that we can identify what's causing the behavior?

**Comment by Originator99** [comment]
> Thanks for the update, @Originator99. Could you provide a sample project that contains this function so that we can identify what's causing the behavior?

Sure @paulinon , I will provide you with a sample project which contains this function.
