### ISSUE TITLE
[Bug] Crashlytics. Cant upload debug symbols. java.io.IOException: Unknown error while sending file, check network response: 400 HTTP/1.1 400 Bad Request]

### ISSUE THREAD

**Issue by sshumihin** [firebase/quickstart-unity#1255]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.1.13f
  * Firebase Unity SDK version: 8.9.0.
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: Crashlytics
  * Other Firebase Components in use: Analytics, RemoteConfig
  * Additional SDKs you are using: Facebook, Appmetrica
  * Platform you are using the Unity editor on: Mac, Windows
  * Platform you are targeting: iOS, Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

During several days I have tried to upload debug symbols with FIrebase CLI and an error raised
 
> firebase crashlytics:symbols:upload --app=15608**** d:\pathtofile_173394-1.7.3-v394.symbols.zip
i  Generating symbols for pathtofile_173394-1.7.3-v394.symbols.zip
i  Generated symbol file: C:\Users\me\AppData\Local\Temp\crashlytics-4d5dc225-abfa-4e10-9245-607c61891034\nativeSymbols\156083734058\breakpad\il2cpp.dbg-arm64-d0d406867cca93986df5afaeba2fc3318c6b45a0.sym (73,420,270 bytes)
i  Uploading all generated symbols
!  [CRASHLYTICS LOG DEBUG] Invoked Crashlytics Buildtools with arguments:
        -verbose true
        -symbolFileCacheDir C:\Users\me\AppData\Local\Temp\crashlytics-4d5dc225-abfa-4e10-9245-607c61891034\nativeSymbols\156083734058\breakpad
        -uploadNativeSymbols true
        -symbolGenerator breakpad
        -googleAppId 15608*****
[CRASHLYTICS LOG DEBUG] Crashlytics Buildtools initialized.
[CRASHLYTICS LOG DEBUG] Uploading native symbol files from directory: C:\Users\me\AppData\Local\Temp\crashlytics-4d5dc225-abfa-4e10-9245-607c61891034\nativeSymbols\156083734058\breakpad
[CRASHLYTICS LOG DEBUG] PUT file: C:\Users\me\AppData\Local\Temp\crashlytics-4d5dc225-abfa-4e10-9245-607c61891034\nativeSymbols\156083734058\breakpad\il2cpp.dbg-arm-c123a8d19ad133abfcfb795b891f33cf214e04c0.gz to URL: https://firebasecrashlyticssymbols.googleapis.com/v1/project/-/app/156083734058/upload/breakpad/c123a8d19ad133abfcfb795b891f33cf214e04c0
[CRASHLYTICS LOG DEBUG] PUT headers:
[CRASHLYTICS LOG DEBUG]         User-Agent = crashlytics-buildtools/2.8.0
[CRASHLYTICS LOG DEBUG]         X-CRASHLYTICS-API-CLIENT-TYPE = crashlytics-buildtools
[CRASHLYTICS LOG DEBUG]         X-CRASHLYTICS-API-CLIENT-VERSION = 2.8.0
[CRASHLYTICS LOG DEBUG] PUT response: [reqId=null] 400
java.io.IOException: Unknown error while sending file, check network [C:\Users\me\AppData\Local\Temp\crashlytics-4d5dc225-abfa-4e10-9245-607c61891034\nativeSymbols\156083734058\breakpad\il2cpp.dbg-arm-c123a8d19ad133abfcfb795b891f33cf214e04c0.gz; response: 400 HTTP/1.1 400 Bad Request]
        at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.sendFile(RestfulWebApi.java:109)
        at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.uploadFile(RestfulWebApi.java:119)
        at com.google.firebase.crashlytics.buildtools.api.FirebaseSymbolFileService.uploadNativeSymbolFile(FirebaseSymbolFileService.java:35)
        at com.google.firebase.crashlytics.buildtools.Buildtools.uploadNativeSymbolFiles(Buildtools.java:266)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeUploadSymbols(CommandLineHelper.java:160)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.doMain(CommandLineHelper.java:107)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:61)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:113)

I tried to upload from other computers (Win 10, Mac), and got same error.

**Comment by paulinon** [comment]
Hi @sshumihin,

Thanks for reporting this. Are you facing a similar issue when using a different network connection? If so, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your implementation along with the complete steps taken to replicate the issue so that we can identify what's causing this behavior.

**Comment by sshumihin** [comment]
Hi,
I have tried with WiFi and LAN from other locations (countries, no VPN).
What I should provide to reproduce? My firebase account? A debug symbols file? It's size over 1Gb. I don't know.

**Comment by sshumihin** [comment]
Hello.
It's my mistake. I used a wrong APP_ID. Unfortunately, the error message doesn't explain me a reason of the exception.

Good day, guys.

**Comment by paulinon** [comment]
Good to hear that you found what's causing the issue, @sshumihin. That being said, I'll be closing this for now. Let me know if an issue arises.
