### ISSUE TITLE
[ANR] JniNativeApi com.google.firebase.crashlytics.ndk.JniNativeApi.<clinit>

### ISSUE THREAD

**Issue by fdspbsteam** [firebase/quickstart-unity#1311]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2020.3.40f1
  * Firebase Unity SDK version: com.google.firebase.app-9.4.0
  * Source you installed the SDK: com.google.firebase.app-9.4.0.tgz
  * Problematic Firebase Component: CrashlyticsNdk
  * Other Firebase Components in use: crashlytics, messaging, auth, analytics
  * Additional SDKs you are using: Facebook, AdMob
  * Platform you are using the Unity editor on: MacBook Pro i7
  * Platform you are targeting:  Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

1. run the app and initialize Firebase

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? 
**no**
What's the issue repro rate? (eg 100%, 1/5 etc)
**looks like 3/5**

**Devices**:
![image](https://user-images.githubusercontent.com/77659032/208085153-e27d48eb-168a-4d28-95f4-cf440199e0bd.png)

#### Relevant Code:

```
 FirebaseMessaging.TokenRegistrationOnInitEnabled = true;
Crashlytics.IsCrashlyticsCollectionEnabled = true;
FirebaseAnalytics.SetAnalyticsCollectionEnabled(true);
SetUserId("xxxx");
Crashlytics.SetUserId(xxxx);

FirebaseApp.CheckAndFixDependenciesAsync()
     if (dependencyStatus == DependencyStatus.Available)
            {
                isOk = true;
            }
       }
       
internal static event EventHandler<TokenReceivedEventArgs> TokenReceivedInternal;

public static event EventHandler<MessageReceivedEventArgs> MessageReceived
    FirebaseMessaging.MessageReceived += OnNotificationMessageReceived;
    
private void OnNotificationMessageReceived(object sender, MessageReceivedEventArgs args)
    {
        FMLogger.vCore("Push received");

        if (args != null && args.Message != null)
        {
            string pushId = string.IsNullOrEmpty(args.Message.MessageId) ? "null" : args.Message.MessageId;
            AppState.PushNotificationId = pushId;

            var data = args.Message.Data;
            if (data != null)
            {
                
              
            }
        }
        else
        {
            Debug.LogError("empty");
        }
    }
```

``` 
# Crashlytics - Stack trace
# Application: 
# Platform: android


Signal Catcher (runnable):tid=3 systid=18535 
#00 pc 0x5392bc libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool) + 124)
#01 pc 0x67197c libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const + 380)
#02 pc 0x692733 libart.so (art::DumpCheckpoint::Run(art::Thread*) + 1091)
#03 pc 0x68bb13 libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*) + 563)
#04 pc 0x68abf9 libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool) + 1801)
#05 pc 0x68a10b libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 827)
#06 pc 0x627149 libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) + 201)
#07 pc 0x63d154 libart.so (art::SignalCatcher::HandleSigQuit() + 1764)
#08 pc 0x63bf25 libart.so (art::SignalCatcher::Run(void*) + 357)
#09 pc 0x10628d libc.so (__pthread_start(void*) + 61)
#10 pc 0xa1127 libc.so (__start_thread + 55)

main (native):tid=1 systid=18531 
#00 pc 0x2e7833 libhoudini.so 
#01 pc 0x2ea61e libhoudini.so 
#02 pc 0x1ee73a libhoudini.so 
#03 pc 0x30896f libhoudini.so 
#04 pc 0x362f64 libhoudini.so 
#05 pc 0x1e5e3 libnativeloader.so (android::NativeLoaderNamespace::Load(char const*) const + 67)
#06 pc 0x112d5 libnativeloader.so (OpenNativeLibraryInNamespace + 69)
#07 pc 0x10be7 libnativeloader.so (OpenNativeLibrary + 135)
#08 pc 0x41490a libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) + 2490)
#09 pc 0x5d36 libopenjdkjvm.so (JVM_NativeLoad + 406)
       at java.lang.Runtime.nativeLoad(Runtime.java)
       at java.lang.Runtime.nativeLoad(Runtime.java:1131)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1085)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
       at java.lang.System.loadLibrary(System.java:1664)
       at com.google.firebase.crashlytics.ndk.JniNativeApi.<clinit>(JniNativeApi.java:49)
       at com.google.firebase.crashlytics.ndk.FirebaseCrashlyticsNdk.create(FirebaseCrashlyticsNdk.java:33)
       at com.google.firebase.crashlytics.ndk.CrashlyticsNdkRegistrar.buildCrashlyticsNdk(CrashlyticsNdkRegistrar.java:45)
       at com.google.firebase.crashlytics.ndk.CrashlyticsNdkRegistrar.lambda$Pjkt4zQ7jb-U0_I19nksvJJlmaM(CrashlyticsNdkRegistrar.java)
       at com.google.firebase.crashlytics.ndk.-$$Lambda$CrashlyticsNdkRegistrar$Pjkt4zQ7jb-U0_I19nksvJJlmaM.create(-.java)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
       at com.google.firebase.components.-$$Lambda$ComponentRuntime$CLI-XObGztS2iu7RD22eoA3PpJU.get(-.java)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.crashlytics.internal.CrashlyticsNativeComponentDeferredProxy.lambda$new$0(CrashlyticsNativeComponentDeferredProxy.java:39)
       at com.google.firebase.crashlytics.internal.-$$Lambda$CrashlyticsNativeComponentDeferredProxy$7NRuOGLlJiZHqRwz-2rcS10so9w.handle(-.java)
       at com.google.firebase.components.OptionalProvider.whenAvailable(OptionalProvider.java:77)
       at com.google.firebase.crashlytics.internal.CrashlyticsNativeComponentDeferredProxy.<init>(CrashlyticsNativeComponentDeferredProxy.java:36)
       at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:79)
       at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:57)
       at com.google.firebase.crashlytics.CrashlyticsRegistrar.lambda$aBuXIXlTYD2Kajd_VBsZ-5OANwA(CrashlyticsRegistrar.java)
       at com.google.firebase.crashlytics.-$$Lambda$CrashlyticsRegistrar$aBuXIXlTYD2Kajd_VBsZ-5OANwA.create(-.java)
       at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
       at com.google.firebase.components.-$$Lambda$ComponentRuntime$CLI-XObGztS2iu7RD22eoA3PpJU.get(-.java)
       at com.google.firebase.components.Lazy.get(Lazy.java:53)
       at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
       at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
       at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:594)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:305)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:269)
       at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:254)
       at com.google.firebase.provider.FirebaseInitProvider.safedk_FirebaseInitProvider_onCreate_00b44787a2c632d77484b8aaa413d1ca(FirebaseInitProvider.java:51)
       at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
       at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7268)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6809)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6726)
       at android.app.ActivityThread.access$1400(ActivityThread.java:237)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

HeapTaskDaemon (waiting):tid=5 systid=18537 
#00 pc 0x9c3d6 libc.so (syscall + 22)
#01 pc 0x20ba3e libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 110)
#02 pc 0x362a11 libart.so (art::gc::TaskProcessor::GetTask(art::Thread*) + 545)
#03 pc 0x363308 libart.so (art::gc::TaskProcessor::RunAllTasks(art::Thread*) + 72)
       at dalvik.system.VMRuntime.runHeapTasks(VMRuntime.java)
       at java.lang.Daemons$HeapTaskDaemon.runInternal(Daemons.java:531)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:923)

Jit thread pool worker thread 0 (native):tid=6 systid=18536 
#00 pc 0x9c3d6 libc.so (syscall + 22)
#01 pc 0x20ba3e libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 110)
#02 pc 0x694675 libart.so (art::ThreadPool::GetTask(art::Thread*) + 101)
#03 pc 0x6937b3 libart.so (art::ThreadPoolWorker::Run() + 67)
#04 pc 0x6932fb libart.so (art::ThreadPoolWorker::Callback(void*) + 267)
#05 pc 0x10628d libc.so (__pthread_start(void*) + 61)
#06 pc 0xa1127 libc.so (__start_thread + 55)

ReferenceQueueDaemon (waiting):tid=7 systid=18538 
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:923)

FinalizerDaemon (waiting):tid=8 systid=18539 
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:190)
       at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:211)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:273)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:923)

FinalizerWatchdogDaemon (waiting):tid=9 systid=18540 
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$FinalizerWatchdogDaemon.sleepUntilNeeded(Daemons.java:341)
       at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:321)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:923)

Binder:18531_1 (native):tid=10 systid=18541 
#00 pc 0xf0be7 libc.so (__ioctl + 7)
#01 pc 0xa8b78 libc.so (ioctl + 216)
#02 pc 0x56e0f libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 319)
#03 pc 0x57010 libbinder.so (android::IPCThreadState::getAndExecuteCommand() + 16)
#04 pc 0x57a5d libbinder.so (android::IPCThreadState::joinThreadPool(bool) + 45)
#05 pc 0x7e467 libbinder.so (android::PoolThread::threadLoop() + 23)
#06 pc 0x15f9f libutils.so (android::Thread::_threadLoop(void*) + 319)
#07 pc 0xb7daf libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*) + 143)
#08 pc 0x15810 libutils.so (thread_data_t::trampoline(thread_data_t const*) + 416)
#09 pc 0x10628d libc.so (__pthread_start(void*) + 61)
#10 pc 0xa1127 libc.so (__start_thread + 55)

Binder:18531_2 (native):tid=11 systid=18542 
#00 pc 0xf0be7 libc.so (__ioctl + 7)
#01 pc 0xa8b78 libc.so (ioctl + 216)
#02 pc 0x56e0f libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 319)
#03 pc 0x57010 libbinder.so (android::IPCThreadState::getAndExecuteCommand() + 16)
#04 pc 0x57a5d libbinder.so (android::IPCThreadState::joinThreadPool(bool) + 45)
#05 pc 0x7e467 libbinder.so (android::PoolThread::threadLoop() + 23)
#06 pc 0x15f9f libutils.so (android::Thread::_threadLoop(void*) + 319)
#07 pc 0xb7daf libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*) + 143)
#08 pc 0x15810 libutils.so (thread_data_t::trampoline(thread_data_t const*) + 416)
#09 pc 0x10628d libc.so (__pthread_start(void*) + 61)
#10 pc 0xa1127 libc.so (__start_thread + 55)

Binder:18531_3 (native):tid=12 systid=18546 
#00 pc 0xf0be7 libc.so (__ioctl + 7)
#01 pc 0xa8b78 libc.so (ioctl + 216)
#02 pc 0x56e0f libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 319)
#03 pc 0x57010 libbinder.so (android::IPCThreadState::getAndExecuteCommand() + 16)
#04 pc 0x57a5d libbinder.so (android::IPCThreadState::joinThreadPool(bool) + 45)
#05 pc 0x7e467 libbinder.so (android::PoolThread::threadLoop() + 23)
#06 pc 0x15f9f libutils.so (android::Thread::_threadLoop(void*) + 319)
#07 pc 0xb7daf libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*) + 143)
#08 pc 0x15810 libutils.so (thread_data_t::trampoline(thread_data_t const*) + 416)
#09 pc 0x10628d libc.so (__pthread_start(void*) + 61)
#10 pc 0xa1127 libc.so (__start_thread + 55)

Profile Saver (native):tid=13 systid=18630 
#00 pc 0x9c3d6 libc.so (syscall + 22)
#01 pc 0x20ba3e libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 110)
#02 pc 0x3dbe72 libart.so (art::ProfileSaver::Run() + 482)
#03 pc 0x3e1ebb libart.so (art::ProfileSaver::RunProfileSaverThread(void*) + 171)
#04 pc 0x10628d libc.so (__pthread_start(void*) + 61)
#05 pc 0xa1127 libc.so (__start_thread + 55)

Thread-2 (timed waiting):tid=15 systid=18673 
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at com.google.android.gms.common.BlockingServiceConnection.getServiceWithTimeout(BlockingServiceConnection.java:3)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzb(AdvertisingIdClient.java:14)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(AdvertisingIdClient.java:3)
       at com.safedk.android.internal.DeviceData.a(DeviceData.java:219)
       at com.safedk.android.internal.DeviceData.a(DeviceData.java:36)
       at com.safedk.android.internal.DeviceData$1.run(DeviceData.java:101)
       at java.lang.Thread.run(Thread.java:923)

Thread-3 (timed waiting):tid=16 systid=18756 
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
       at com.google.android.gms.common.BlockingServiceConnection.getServiceWithTimeout(BlockingServiceConnection.java:3)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzb(AdvertisingIdClient.java:14)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(AdvertisingIdClient.java:3)
       at com.applovin.impl.sdk.utils.d.d(d.java)
       at com.applovin.impl.sdk.utils.d.c(d.java)
       at com.applovin.impl.sdk.utils.d.b(d.java)
       at com.applovin.impl.sdk.utils.d.a(d.java)
       at com.applovin.impl.sdk.p$1.run(p.java)
       at java.lang.Thread.run(Thread.java:923)

GoogleApiHandler (native):tid=17 systid=18760 
#00 pc 0xf1baa libc.so (__epoll_pwait + 10)
#01 pc 0x1a3d9 libutils.so (android::Looper::pollInner(int) + 249)
#02 pc 0x1a27e libutils.so (android::Looper::pollOnce(int, int*, int*, void**) + 126)
#03 pc 0x125933 libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int) + 35)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:183)
       at android.os.HandlerThread.run(HandlerThread.java:67)

pool-4-thread-1 (timed waiting):tid=14 systid=18762 
       at sun.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2109)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:849)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1092)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by fdspbsteam** [comment]
wrong repository
https://github.com/firebase/firebase-unity-sdk/issues/578

**Comment by fdspbsteam** [comment]
wrong repository
https://github.com/firebase/firebase-unity-sdk/issues/578

**Comment by Ihtyijfd** [comment]
در تاریخ جمعه ۱۶ دسامبر ۲۰۲۲،‏ ۱۵:۱۰ Google Open Source Bot <
***@***.***> نوشت:
