### ISSUE TITLE
Cannot upload debug symbols for Android to crashlytics

### ISSUE THREAD

**Issue by beginner-lang** [firebase/quickstart-unity#1355]
### [READ] For Firebase Unity SDK issues, please report to [Firebase Unity open-source](https://github.com/firebase/firebase-unity-sdk/issues/new/choose)

Once you've read this section and determined that your issue is appropriate for this repository, please delete this section.

### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.3.3f1
  * Firebase Unity SDK version: 11.2.0
  * Source you installed the SDK: .unitypackage
  * Problematic Firebase Component: FirebaseAnalytics
  * Other Firebase Components in use: 
  * Additional SDKs you are using: Facebook
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:
Unity exports the AndroidStudio project, generates symbols.zip file, and uses the CMD:firebase crashlytics:symbols:upload --app=projectName-idString D:\36227-v27.symbols.zip
It will make an error

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
logcat:
[CRASHLYTICS LOG DEBUG] PUT headers:
[CRASHLYTICS LOG DEBUG]         User-Agent = firebase-cli;crashlytics-buildtools/2.9.2
[CRASHLYTICS LOG DEBUG]         X-CRASHLYTICS-API-CLIENT-TYPE = firebase-cli;crashlytics-buildtools
[CRASHLYTICS LOG DEBUG]         X-CRASHLYTICS-API-CLIENT-VERSION = 2.9.2
javax.net.ssl.SSLProtocolException: Connection reset
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.google.firebase.crashlytics.buildtools.reloc.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.sendFile(RestfulWebApi.java:100)
        at com.google.firebase.crashlytics.buildtools.api.RestfulWebApi.uploadFile(RestfulWebApi.java:119)
        at com.google.firebase.crashlytics.buildtools.api.FirebaseSymbolFileService.uploadNativeSymbolFile(FirebaseSymbolFileService.java:35)
        at com.google.firebase.crashlytics.buildtools.Buildtools.uploadNativeSymbolFiles(Buildtools.java:301)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeUploadSymbols(CommandLineHelper.java:194)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:120)
        at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
        at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)
Caused by: java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        ... 24 more
Error: java command failed with args: -jar,C:\Users\user\.cache\firebase\crashlytics\buildtools\crashlytics-buildtools-2.9.2.jar,-symbolGenerator,breakpad,-symbolFileCacheDir,C:\Users\user\AppData\Local\Temp\crashlytics-25999287-c29b-4fc9-bb93-e08a0f53b358\nativeSymbols\roguelikealice-7a394\breakpad,-verbose,-uploadNativeSymbols,-googleAppId,roguelikealice-7a394,-clientName,firebase-cli;crashlytics-buildtools

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
What's the issue repro rate? (eg 100%, 1/5 etc)

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by beginner-lang** [comment]
After checking Create symbols.zip, I choose to export ExportProject. The symbols.zip file appears in the AndroidStudio project sibling directory, I don't know if it is the file I need.

After I built AAB with AndroidStudio, there is no unityLibrary/Symbols directory. I don't know what's wrong with me
