### ISSUE TITLE
Can't merge manifests

### ISSUE THREAD

**Issue by Temka193** [firebase/quickstart-unity#175]
Import cloud messaging in empty project and resolve dependencies with "Play services resolver" and build in Unity with internal build system.

Result:

> CommandInvokationFailure: Unable to merge android manifests. 
> C:/Program Files/Java/jdk1.8.0_121\bin\java.exe -Xmx2048M -
> Dcom.android.sdkmanager.toolsdir="C:/Users/Максим/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files
> \Unity2017_4\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -
> 
> stderr[
> Error: [Temp\StagingArea\AndroidManifest-main.xml, D:
> \UnityProjects\TestProject\Temp\StagingArea\android-libraries\com.google.firebase.firebase-measurement-connector-impl-
> 16.0.1\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/service
> [@name=com.google.firebase.components.ComponentDiscoveryService] element:
>   <service @android:name="com.google.firebase.components.ComponentDiscoveryService">
>       <meta-data
> —        
> @android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
>   <service @android:name="com.google.firebase.components.ComponentDiscoveryService">
>       <meta-data
> ++        
> @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
> ]

**Comment by stewartmiles** [comment]
Yep this is a duplicate of #172, we're working on it.

**Comment by jnroesch** [comment]
I still get the same error with unity 2018.1.6f1 (with 4.x runtime Version) and firebase sdk 5.1.1

**Comment by EvilNeru** [comment]
@stewartmiles 
We still get this issue on our project seemingly out of the blue with a long working Firebase setup with Unity 2017.1.2p3 using Firebase sdk 5.1.1 when using "internal"

> CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:/Program Files/Java/jdk1.8.0_161\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/rory.aguilar/AppData/Local/Android/Sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Hub\Editor\2017.2.1f1\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -
stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Projects\REDACTED\Temp\StagingArea\android-libraries\com.google.firebase.firebase-iid-16.0.0\AndroidManifest.xml:11] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Projects\REDACTED\Temp\StagingArea\android-libraries\com.google.firebase.firebase-measurement-connector-impl-16.0.1\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml, C:\Projects\REDACTED\Temp\StagingArea\android-libraries\com.android.support.support-core-ui-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Projects\REDACTED\Temp\StagingArea\android-libraries\com.android.support.support-core-utils-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Projects\REDACTED\Temp\StagingArea\android-libraries\com.android.support.support-fragment-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Projects\REDACTED\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Projects\REDACTED\Temp\StagingArea\android-libraries\com.android.support.support-v4-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Projects\REDACTED\Temp\StagingArea\android-libraries\com.google.firebase.firebase-analytics-impl-16.1.1\AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.BuildPipeline:BuildPlayer(BuildPlayerOptions) (at ?)
AssetBundles.BuildScript:BuildFromBuildUserData(BuildUserData) (at Assets/GameTools/AssetBundleManager/Editor/BuildScript.cs:193)
AssetBundles.BuildWindow:OnGUI() (at Assets/GameTools/AssetBundleManager/Editor/BuildWindow.cs:180)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at ?)


If we switch the project over to "gradle", the build finished fine. At runtime we get the following which is #136 

> 07-11 19:08:30.009 2577-2608/? E/Unity: Unable to find /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
07-11 19:08:30.157 2577-2577/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ff0000.crayola, PID: 2577
    java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 2017.1.2p3
    Device model      : samsung SM-T820
    Device fingerprint: samsung/gts3lwifixx/gts3lwifi:7.0/NRD90M/T820XXU1AQI2:user/release-keys
    
    Caused by: java.lang.AbstractMethodError: abstract method "void com.google.firebase.auth.FirebaseAuth$AuthStateListener.a(com.google.firebase.auth.FirebaseAuth)"
        at com.google.firebase.auth.t.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6780)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

Interestingly, if we take the quickstart-unity/auth projects and simply add the FirebaseAnalytics.unitypackage and build "internal" we get the "ComponentDiscoveryService" merge manifest error as above.

And if we take the quickstart-unity/auth projects and simply add the FirebaseMessaging.unitypackage we get this error, which appears to be #172 

> * What went wrong:
Cannot read packageName from C:\TestProjects\quickstart-unity-master\auth\testapp\Temp\gradleOut\src\main\AndroidManifest.xml

It seems that all these persistent problems seem to be interrelated. This whole situation is destroying our project's productivity.

**Comment by stewartmiles** [comment]
@EvilNeru I'm trying to unpack what you've pasted in here.

If I'm reading this correctly, in 2017.1.2p3 you grab our auth sample:
- Import the FirebaseAuth.unitypackage
- Import the FirebaseMessaging.unitypackage
- Download and add google-services.json file to the project.
- Switch the build target to Android
- Select the "Internal" build option (if required, it's the default option AFAIK)
- Build

then the build fails with a manifest merge error correct?

I just followed the above steps and I'm able to build and run on an Android device with no issues.

**Comment by EvilNeru** [comment]
I apologize for the confusing way I wrote the above post. I our current project we are suddenly running into the following issues when building Android:
`Unity 2017.1.2p3 using Firebase sdk 5.1.1`
- When Using "Internal" build option we get this issue #175
- When Using "Gradle" build option we get the issue #136 


In an effort to get our current project working again on Android, I started doing testing on the quickstart-unity/auth project with the setup:
`Unity 2018.2.0f2 using Firebase sdk 5.1.1`

- Import **FirebaseAuth.unitypackage**
- Building with **Gradle** works
- Building with **Internal** yields this issue #175

After importing in more packages (but not always), I get the issue #172 ("Gradle build failed. See the Console for details") and cannot effectively build the demo anymore using **Gradle**. It is unclear to me what causes this to occur as I cannot reliably reproduce it . Could it be the switching back and forth from **Gradle** to **Internal** is leaving some intermediate files?

Ultimately the goal is to resolve #136 happening on our actual project but this has sucked me down Android build rabbit hole.

**Comment by stewartmiles** [comment]
@EvilNeru is it possible you have auto-resolution disabled in the Android Resolver settings?  When switching between Gradle vs. Internal builds, resolution needs to be executed again and AARs / JARs need to be processed to support the build configuration.  With auto-resolution enabled, the Android Resolver plugin will trigger auto-resolution ~3 seconds after switching the build config.

If you can, it would be useful to share an archive of the project in the bad state.  i.e after you've built with gradle, switched to internal and built again.

**Comment by lluma** [comment]
Sorry, I got the same issue on Unity 5.6.2f1 with Firebase 5.2.0 SDK

`CommandInvokationFailure: Unable to merge android manifests. See the Console for more details. 
C:/Program Files/Java/jdk1.8.0_161\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/CGVLAB-02/AppData/Local/Android/Sdk-old\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\CGVLAB-02\Desktop\ConstructPlane-master\Temp\StagingArea\android-libraries\com.google.firebase.firebase-iid-16.0.0\AndroidManifest.xml:11] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Users\CGVLAB-02\Desktop\ConstructPlane-master\Temp\StagingArea\android-libraries\com.google.firebase.firebase-measurement-connector-impl-16.0.1\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
]
stdout[
Warning: [Temp\StagingArea\AndroidManifest-main.xml:4, C:\Users\CGVLAB-02\Desktop\ConstructPlane-master\Temp\StagingArea\android-libraries\android.arch.lifecycle.runtime-1.0.0\AndroidManifest.xml:3] Main manifest has <uses-sdk android:targetSdkVersion='23'> but library uses targetSdkVersion='26'
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\CGVLAB-02\Desktop\ConstructPlane-master\Temp\StagingArea\android-libraries\com.android.support.support-core-ui-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\CGVLAB-02\Desktop\ConstructPlane-master\Temp\StagingArea\android-libraries\com.android.support.support-core-utils-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\CGVLAB-02\Desktop\ConstructPlane-master\Temp\StagingArea\android-libraries\com.android.support.support-fragment-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\CGVLAB-02\Desktop\ConstructPlane-master\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\CGVLAB-02\Desktop\ConstructPlane-master\Temp\StagingArea\android-libraries\com.android.support.support-v4-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Users\CGVLAB-02\Desktop\ConstructPlane-master\Temp\StagingArea\android-libraries\com.google.firebase.firebase-analytics-impl-16.1.1\AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
]
exit code: 1
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()`

Is there any way to fix it?

**Comment by exzizt** [comment]
I recently added Firebase Auth, then Database, then GPGS to my project. Today, I added AdMob. That seemed to break everything. I'm at this point now where I'm getting this:

`08-01 04:06:21.857 25234 25234 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at com.google.games.bridge.TokenFragment.buildClient(TokenFragment.java:382)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at com.google.games.bridge.TokenFragment.processRequest(TokenFragment.java:279)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at com.google.games.bridge.TokenFragment.onResume(TokenFragment.java:506)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.app.Fragment.performResume(Fragment.java:2272)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.app.BackStackRecord.run(BackStackRecord.java:793)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5551)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
08-01 04:06:21.857 25234 25234 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.exzizt.Birdie-1/base.apk"],nativeLibraryDirectories=[/data/app/com.exzizt.Birdie-1/lib/arm, /data/app/com.exzizt.Birdie-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        ... 17 more
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.api.Api$zzf
08-01 04:06:21.857 25234 25234 E AndroidRuntime:                at java.lang.Class.classForName(Native Method)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
08-01 04:06:21.857 25234 25234 E AndroidRuntime:                ... 18 more
08-01 04:06:21.857 25234 25234 E AndroidRuntime:        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

What do I do?

**Comment by stewartmiles** [comment]
@exzizt we're discussing this on #192

**Comment by btaller** [comment]
Oh yea here is the error, but this component isn't referenced in any of the manifests!

CommandInvokationFailure: Unable to merge android manifests. 
C:\Program Files\Java\jdk1.8.0_131\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/btall/AppData/Local/Android/Sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: [Temp\StagingArea\AndroidManifest-main.xml, C:\Code\Unity\LaserForce3D\Laser Force 3D\Temp\StagingArea\android-libraries\com.google.firebase.firebase-measurement-connector-impl-16.0.1\AndroidManifest.xml:10] Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
--        @android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
  <service
      @android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
]
stdout[
[Temp\StagingArea\AndroidManifest-main.xml, C:\Code\Unity\LaserForce3D\Laser Force 3D\Temp\StagingArea\android-libraries\com.android.support.support-core-ui-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Code\Unity\LaserForce3D\Laser Force 3D\Temp\StagingArea\android-libraries\com.android.support.support-core-utils-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Code\Unity\LaserForce3D\Laser Force 3D\Temp\StagingArea\android-libraries\com.android.support.support-fragment-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Code\Unity\LaserForce3D\Laser Force 3D\Temp\StagingArea\android-libraries\com.android.support.support-media-compat-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Code\Unity\LaserForce3D\Laser Force 3D\Temp\StagingArea\android-libraries\com.android.support.support-v4-26.1.0\AndroidManifest.xml:6] Skipping identical /manifest/application/meta-data[@name=android.support.VERSION] element.
[Temp\StagingArea\AndroidManifest-main.xml, C:\Code\Unity\LaserForce3D\Laser Force 3D\Temp\StagingArea\android-libraries\com.google.firebase.firebase-analytics-impl-16.1.1\AndroidManifest.xml:12] Skipping identical /manifest/application/receiver[@name=com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver] element.
]

**Comment by btaller** [comment]
I commented out these lines:
 

and it works.  I haven't actually tested it yet..and this may break something else but it compiled correctly..lets find out..

**Comment by btaller** [comment]
<service android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data android:name="com.google.firebase.components:com.google.firebase.iid.Registrar" android:value="com.google.firebase.components.ComponentRegistrar" />
    </service>

**Comment by btaller** [comment]
` `

**Comment by yassinya** [comment]
Did it work? @btaller

**Comment by IsnaniWidhiHidayat** [comment]
I have same problem to, and I try to combine all like this in AndroidManifest at Assets\Plugins\Android\com.google.firebase.firebase-iid-16.2.0

` <service android:name="com.google.firebase.components.ComponentDiscoveryService">
      <meta-data 
      	android:name="com.google.firebase.components:com.google.firebase.iid.Registrar" 
      	android:value="com.google.firebase.components.ComponentRegistrar" />   
    <meta-data
android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
        android:value="com.google.firebase.components.ComponentRegistrar" />
    <meta-data
        android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
        android:value="com.google.firebase.components.ComponentRegistrar" />
</service>`

then delete all service on file 'com.google.firebase.firebase-measurement-connector-impl-16.0.1.aar' and  'com.google.firebase.firebase-auth-16.0.2.aar'. you can delete by open file with 7zip or winrar and edit androidmanifest file on it.

**Comment by elusiven** [comment]
I have the same error on Unity 2017.4.6f1 and newest firebase sdk. Any help please?

**Comment by bourgeoismaxime** [comment]
Same issue with Firebase SDK 5.3.1 Analytics and Unity 2018.2.8f1 using an empty project and only FirebaseAnalytics.unitypackage imported.
Works with Build System set to Gradle but not when set to Internal.

> Trying to merge incompatible /manifest/application/service[@name=com.google.firebase.components.ComponentDiscoveryService] element:
  <service
--    @android:exported="false"
--    @android:name="com.google.firebase.components.ComponentDiscoveryService">
--    <meta-data
  <service
++    @android:name="com.google.firebase.components.ComponentDiscoveryService">
++    <meta-data
++        @android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"

**Comment by stewartmiles** [comment]
@bourgeoismaxime as I mentioned in https://github.com/firebase/quickstart-unity/issues/192#issuecomment-415622826 manifest merge errors can be a result of an old Android SDK being used.  In addition, if you switch build target and have [auto-resolution](https://github.com/googlesamples/unity-jar-resolver#auto-resolution) in the Android Resolver or you don't *Force Resolve* after switching build target to reprocess the AARs/JARs you'll run into this issue.

**Comment by deltamish** [comment]
Same Issue Here. using Unity 2017.4 . Assets-> PlayServiceResolver -> resolution Sucessfull 
file Build[Internal] -> Build failed :Can't merge manifests error 

@firebase-ops 
Its urgent kindly help resolve it. We are suffering huge delay in deployment 

Thanks

**Comment by stewartmiles** [comment]
@deltamish see the resolution in https://github.com/firebase/quickstart-unity/issues/192#issuecomment-415622826
