### ISSUE TITLE
Firebase crash when resume app from background in Android

### ISSUE THREAD

**Issue by NhamPhanDinh** [firebase/quickstart-unity#18]
Hi,
I have used Firebase for my game.
When i press home button, and open again game, my game crash,
and i also log error:

>  E/AndroidRuntime: FATAL EXCEPTION: IntentService[FIREBASE_MSG_FWDR]
                                                 java.lang.Error: FATAL EXCEPTION [IntentService[FIREBASE_MSG_FWDR]]
                                                 Unity version     : 5.4.3f1
                                                 Device model      : samsung Galaxy Nexus
                                                 
                                                 Caused by: java.lang.NullPointerException
                                                     at com.google.firebase.messaging.RemoteMessage.getFrom(Unknown Source)
                                                     at com.google.firebase.messaging.cpp.ListenerService.onMessageReceived(ListenerService.java:59)
                                                     at com.google.firebase.messaging.MessageForwardingService.onHandleIntent(MessageForwardingService.java:34)
                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by stewartmiles** [comment]
This is a cross post of the issue reported on
https://groups.google.com/d/msg/firebase-talk/rqWZ2frS_VY/ISNmhzfFAwAJ

**Comment by BuKuSiShen** [comment]
I also get this bug on Android device.How to fix this issue?

**Comment by NhamPhanDinh** [comment]
Haha, i thing wait developer of FIrebase fix it in next release, i'm also hope they can release early

**Comment by BuKuSiShen** [comment]
Thank you.Maybe just wait the next social release.

**Comment by BuKuSiShen** [comment]
Hello NhamPhanDinh!Do you get that issue ?In the Unity game,when I use SceneManager.LoadSceneAsync("MenuScene") then I can't receive the message data from OnMessageReceived in the appliocation.But can also receive push notifiction on the mobile device list.

**Comment by stewartmiles** [comment]
I'm pleased to announce that we released:

- Firebase C++ SDK 2.1.0 (release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#2.1.0), download [here](https://firebase.google.com/docs/cpp/setup))
- Firebase Unity SDK 1.1.0 (release notes [here](https://firebase.google.com/support/release-notes/unity#1.1.0), download [here](https://firebase.google.com/docs/unity/setup))

I believe this should resolve your issue.  If not, please let us know and we'll take a look.

Cheers,
Stewart

**Comment by BuKuSiShen** [comment]
@stewartmiles yeah.Thank you for having solved the two issues.Now I have found the other issue that I can't receive the fcm push notification when EXIT the game,only receive fcm push notification when the unity app is active.

**Comment by stewartmiles** [comment]
See https://github.com/firebase/quickstart-unity/issues/25
