### ISSUE TITLE
Unity - Firebase push notifications & gps 

### ISSUE THREAD

**Issue by pancar** [firebase/quickstart-unity#251]
Hi,
my unity ver is 2018 16f1
gps 0.9.50 (i getting auth token only with this version)
firebase (I've tried with 5.2.0 & 5.4.2)
play services resolver 1.2.95

when do i import the firebase plugin, gps stopped working.

what i need to do ?

Thanks...

log:

 Java class com/google/firebase/FirebaseApp not found.  Please verify the AAR which contains the com/google/firebase/FirebaseApp class is included in your app.
11-21 01:14:18.915 32761   341 E Unity   :  
11-21 01:14:18.915 32761   341 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:18.915 32761   341 E Unity   : 
11-21 01:14:18.915 32761   341 E Unity   : clazz
11-21 01:14:18.915 32761   341 E Unity   :  
11-21 01:14:18.915 32761   341 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:18.915 32761   341 E Unity   : 
11-21 01:14:18.946 32761   341 E Unity   : InitializationException:  Firebase app creation failed.
11-21 01:14:18.946 32761   341 E Unity   :   at Firebase.FirebaseApp.CreateAndTrack (Firebase.CreateDelegate createDelegate, Firebase.FirebaseApp existingProxy) [0x00000] in <filename unknown>:0 
11-21 01:14:18.946 32761   341 E Unity   :   at Firebase.FirebaseApp.Create () [0x00000] in <filename unknown>:0 
11-21 01:14:18.946 32761   341 E Unity   :   at Firebase.FirebaseApp.get_DefaultInstance () [0x00000] in <filename unknown>:0 
11-21 01:14:18.946 32761   341 E Unity   :   at Firebase.Messaging.FirebaseMessaging+Listener..ctor () [0x00000] in <filename unknown>:0 
11-21 01:14:18.946 32761   341 E Unity   :   at Firebase.Messaging.FirebaseMessaging+Listener.Create () [0x00000] in <filename unknown>:0 
11-21 01:14:18.946 32761   341 E Unity   :   at Firebase.Messaging.FirebaseMessaging..cctor () [0x00000] in <filename unknown>:0 
11-21 01:14:18.946 32761   341 E Unity   : Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Firebase.Messaging.FirebaseMessaging
11-21 01:14:18.946 32761   341 E Unity   :   at FirebasePush.Start () [0x00000] in <filename unknown>:0 
11-21 01:14:18.946 32761   341 E Unity   :  
11-21 01:14:18.946 32761   341 E Unity   : (Filename:  Line: -1)
11-21 01:14:18.946 32761   341 E Unity   : 
11-21 01:14:22.193 32761   341 E Unity   : GameSparks Connected...
11-21 01:14:22.193 32761   341 E Unity   :  
11-21 01:14:22.193 32761   341 E Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:22.193 32761   341 E Unity   : 
11-21 01:14:22.213 32761   341 I Unity   : Starting Auth with token client.
11-21 01:14:22.213 32761   341 I Unity   :  
11-21 01:14:22.213 32761   341 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:22.213 32761   341 I Unity   : 
11-21 01:14:22.241 32761   341 W Unity   : !!! [Play Games Plugin DLL] 11/21/18 1:14:22 +03:00 WARNING: Creating new PlayGamesPlatform
11-21 01:14:22.241 32761   341 W Unity   :  
11-21 01:14:22.241 32761   341 W Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:22.241 32761   341 W Unity   : 
11-21 01:14:22.242 32761   341 I Unity   :  [Play Games Plugin DLL] 11/21/18 1:14:22 +03:00 DEBUG: Activating PlayGamesPlatform.
11-21 01:14:22.242 32761   341 I Unity   :  
11-21 01:14:22.242 32761   341 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:22.242 32761   341 I Unity   : 
11-21 01:14:22.242 32761   341 I Unity   :  [Play Games Plugin DLL] 11/21/18 1:14:22 +03:00 DEBUG: PlayGamesPlatform activated: GooglePlayGames.PlayGamesPlatform
11-21 01:14:22.242 32761   341 I Unity   :  
11-21 01:14:22.242 32761   341 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:22.242 32761   341 I Unity   : 
11-21 01:14:22.242 32761   341 I Unity   :  [Play Games Plugin DLL] 11/21/18 1:14:22 +03:00 DEBUG: Creating platform-specific Play Games client.
11-21 01:14:22.242 32761   341 I Unity   :  
11-21 01:14:22.242 32761   341 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:22.242 32761   341 I Unity   : 
11-21 01:14:22.242 32761   341 I Unity   :  [Play Games Plugin DLL] 11/21/18 1:14:22 +03:00 DEBUG: Creating Android IPlayGamesClient Client
11-21 01:14:22.242 32761   341 I Unity   :  
11-21 01:14:22.242 32761   341 I Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:22.242 32761   341 I Unity   : 
11-21 01:14:22.268 32761   341 W Unity   : *** [Play Games Plugin DLL] 11/21/18 1:14:22 +03:00 ERROR: Exception launching token request: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
11-21 01:14:22.268 32761   341 W Unity   :  
11-21 01:14:22.268 32761   341 W Unity   : (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
11-21 01:14:22.268 32761   341 W Unity   : 
11-21 01:14:22.269 32761   341 W Unity   : *** [Play Games Plugin DLL] 11/21/18 1:14:22 +03:00 ERROR: UnityEngine.AndroidJavaException: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
11-21 01:14:22.269 32761   341 W Unity   : java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
11-21 01:14:22.269 32761   341 W Unity   : 	at java.lang.Class.classForName(Native Method)
11-21 01:14:22.269 32761   341 W Unity   : 	at java.lang.Class.forName(Class.java:400)
11-21 01:14:22.269 32761   341 W Unity   : 	at java.lang.Class.forName(Class.java:326)
11-21 01:14:22.269 32761   341 W Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
11-21 01:14:22.269 32761   341 W Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source)
11-21 01:14:22.269 32761   341 W Unity   : 	at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
11-21 01:14:22.269 32761   341 W Unity   : 	at android.os.MessageQueue.next(MessageQueue.java:392)
11-21 01:14:22.269 32761   341 W Unity   : 	at android.os.Looper.loop(Looper.java:136)
11-21 01:14:22.269 32761   341 W Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
11-21 01:14:22.269 32761   341 W Unity   : Caused by: java.lang.ClassNotFoundException: com.google.games.bridge.TokenFragment
11-21 01:14:22.269 32761   341 W Unity   : 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
11-21 01:14:22.269 32761   341 W Unity   : 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
11-21 01:14:22.269 32761   341 W Unity   : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
11-21 01:14:22.269 32761   341 W Unity   : 	at java.lang.ClassLoader.loadClass(ClassLoader.
11-21 01:15:01.018   653   668 I ActivityManager: Start proc 1820:com.android.deskclock/u0a48 for broadcast com.android.deskclock/com.android.alarmclock.DigitalAppWidgetProvider
11-21 01:15:23.586   653  1729 I ActivityManager: Setting hasTopUi=true for pid=845
11-21 01:15:23.679   653 17323 I ActivityManager: Config changes=480 {1.0 286mcc2mnc [en_US] ldltr sw360dp w360dp h616dp 480dpi nrml long port finger -keyb/v/h -nav/h s.167}

**Comment by pancar** [comment]
is there anyone?

**Comment by pancar** [comment]
@stewartmiles thanks, verbose logging solved my problem.
