### ISSUE TITLE
Messaging: on Android Application.Quit always crash

### ISSUE THREAD

**Issue by luisshin** [firebase/quickstart-unity#394]
## Please fill in the following fields:
Unity editor version: 2018.3.14f1
Firebase Unity SDK version: 6.1.1
Firebase plugins in use (Auth, Database, etc.): Messaging
Additional SDKs you are using (Facebook, AdMob, etc.):  none
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

## Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

this is Messeging sample code and import only google-services.json

logcat trace

06-22 11:02:11.341 17010-17799/? I/Unity: Firebase App initializing app [package id] (default 1).
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
06-22 11:02:11.351 17010-17799/? I/Unity: Firebase Cloud Messaging API Initialized
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
06-22 11:02:11.476 17010-17748/? I/Unity: Firebase App initializing app [package id] (default 1).
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
06-22 11:02:11.481 17010-17748/? I/Unity: Firebase Cloud Messaging API Initialized
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
06-22 11:02:11.541 17010-17748/? I/Unity: Firebase Messaging Initialized
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
06-22 11:02:11.551 17010-17748/? I/Unity: Received Registration Token: cfL4aqXjsPk:APA91bFNe2PhPWtxhw9NNFvF6F9l4kbRngcR4NIfL3Sp4FcnjftX-cmtCVZ--m7VX-pfX3vtgtgQy6OCAsiF5SE4ITO3Z0C5WwjWRcABdJHbANpLLWnCQKExv0Kz1hyrUYh3rkRduLms
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
06-22 11:02:11.646 17010-17748/? I/Unity: RequestPermissionAsync completed
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
06-22 11:02:12.351 17010-17748/? I/Unity: SubscribeAsync completed
                                           
                                          (Filename: ./Runtime/Export/Debug.bindings.h Line: 45)
06-22 11:02:14.936 3803-3839/? V/WindowStateAnimator: Finishing drawing window Window{72e9b60 u0 d0 [packge_id]/com.google.firebase.MessagingUnityPlayerActivity}: mDrawState=DRAW_PENDING
06-22 11:02:14.966 3803-4065/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{451f20b u0 [packge_id]/com.google.firebase.MessagingUnityPlayerActivity t91} time:186072050
06-22 11:02:14.976 3803-4065/? I/WindowManager: Screen frozen for +232ms due to Window{72e9b60 u0 d0 [packge_id]/com.google.firebase.MessagingUnityPlayerActivity}
06-22 11:02:17.351 3803-3969/? W/ActivityManager: Activity pause timeout for ActivityRecord{451f20b u0 [packge_id]/com.google.firebase.MessagingUnityPlayerActivity t91 f}
06-22 11:02:17.516 3803-3839/? V/WindowStateAnimator: Finishing drawing window Window{72e9b60 u0 d0 [packge_id]/com.google.firebase.MessagingUnityPlayerActivity}: mDrawState=DRAW_PENDING
06-22 11:02:17.626 17010-17010/? E/ActivityThread: Activity com.google.firebase.MessagingUnityPlayerActivity has leaked ServiceConnection null that was originally bound here
                                                   android.app.ServiceConnectionLeaked: Activity com.google.firebase.MessagingUnityPlayerActivity has leaked ServiceConnection null that was originally bound here
                                                       at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1204)
                                                       at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1098)
                                                       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1412)
                                                       at android.app.ContextImpl.bindService(ContextImpl.java:1395)
                                                       at android.content.ContextWrapper.bindService(ContextWrapper.java:632)
                                                       at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                       at com.unity3d.player.UnityPlayer.c(Unknown Source)
                                                       at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
                                                       at android.os.MessageQueue.next(MessageQueue.java:392)
                                                       at android.os.Looper.loop(Looper.java:143)
                                                       at com.unity3d.player.UnityPlayer$e.run(Unknown Source)

## Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)? yes

**Comment by mironal3x** [comment]
The exact same issue happens on my project's side as well, but on Unity 2019.1.7
Is there any quickfix for this?

**Comment by stewartmiles** [comment]
@luisshin could you share the complete adb logcat output?

You can capture adb logcat output by running the following the console...

`adb logcat -c; adb logcat | tee logcat.log`

then launching the application on the Android device.  You can then attach `logcat.log` to this issue to share the logs.

**Comment by luisshin** [comment]
> @luisshin could you share the complete adb logcat output?
> 
> You can capture adb logcat output by running the following the console...
> 
> `adb logcat -c; adb logcat | tee logcat.log`
> 
> then launching the application on the Android device. You can then attach `logcat.log` to this issue to share the logs.

[logcat.log](https://github.com/firebase/quickstart-unity/files/3328566/logcat.log)

**Comment by stewartmiles** [comment]
All I see in the log is...


```
2019-06-26 15:23:54.588 31169-31169/? E/ActivityThread: Activity com.google.firebase.MessagingUnityPlayerActivity has leaked ServiceConnection $
    android.app.ServiceConnectionLeaked: Activity com.google.firebase.MessagingUnityPlayerActivity has leaked ServiceConnection null that was o$
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1399)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1294)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1520)
        at android.app.ContextImpl.bindService(ContextImpl.java:1492)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:696)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source)
        at android.os.MessageQueue.next(MessageQueue.java:392)
        at android.os.Looper.loop(Looper.java:136)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source)
```

That isn't a crash or ANR as far as I can tell.  Is that the issue you're running into?

**Comment by stewartmiles** [comment]
The SDK doesn't bind a connection to the messaging service, it looks like Unity's activity is doing this and not unbinding when the activity is destroyed.
https://forum.unity.com/threads/application-unload-doesnt-work-as-expected.543616/

This is a warning more than anything else since I don't think the "leak" is really a leak as the application is being shut down at this point.

**Comment by stewartmiles** [comment]
@alexames and I spent some time looking into this today, the only crash we've been able to reproduce was caused by this Unity bug
https://forum.unity.com/threads/crashes-on-huawei-android-9-devices.632944/

**Comment by chkuang-g** [comment]
@luisshin 
Close this issue since it is inactive for a month
Please let us know if you are still experiencing the same crash with the latest SDK.
