### ISSUE TITLE
My application crash when open.

### ISSUE THREAD

**Issue by anhnh1721** [firebase/quickstart-unity#471]
Unity editor version: 2019.2.0f1
Firebase Unity SDK version: 6.5.0
Firebase plugins in use (Auth, Database, etc.): Auth, Database, Message, Analystic
Additional SDKs you are using (Facebook, AdMob, etc.): Facebook, AdMod
Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): Android

Please help. My game crash when open. This is log in logcat:
```

2019-09-15 21:57:11.465 1456-1554/? E/CRASH: pid: 1456, tid: 1554, name: UnityMain  >>> net.bctank.game <<<
2019-09-15 21:57:11.503 1523-1585/? I/GameTools: GameToolsIntentService : TYPE : 0 PKGNAME : net.bctank.game
2019-09-15 21:57:11.510 1523-1585/? I/GameTools: GameToolsIntentService : RESUMED+ , net.bctank.game
2019-09-15 21:57:11.510 1523-1585/? I/GameTools: [GID] : [RPN]:net.bctank.game
2019-09-15 21:57:11.528 1523-1585/? I/GameTools: GameToolsIntentService : RESUMED- , net.bctank.game
2019-09-15 21:57:11.535 5729-5897/? W/InputDispatcher: channel 'd2bfb49 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9, fd=398
2019-09-15 21:57:11.535 5729-5897/? E/InputDispatcher: channel 'd2bfb49 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-09-15 21:57:11.539 5254-5254/? I/SurfaceFlinger: id=449 Removed SurfaceView - net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity@3444c43@0[1456]#0 (1/79)
2019-09-15 21:57:11.539 5729-5739/? I/ActivityManager: Process net.bctank.game (pid 1456) has died: fore TOP (570,3515)
2019-09-15 21:57:11.539 5254-5254/? I/SurfaceFlinger: id=450 Removed Background for -SurfaceView - net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity@3444c43@0[1456]#0 (0/78)
2019-09-15 21:57:11.540 5729-8223/? I/WindowManager: WIN DEATH: Window{d2bfb49 u0 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity}
2019-09-15 21:57:11.541 5729-8223/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'd2bfb49 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity (server)'
2019-09-15 21:57:11.541 5729-8223/? V/WindowManager: Remove Window{d2bfb49 u0 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity}: mSurfaceController=Surface(name=net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity[1456])/@0x5882a80 mAnimatingExit=false mRemoveOnExit=false mHasSurface=true surfaceShowing=true isAnimationSet=false app-animation=false mWillReplaceWindow=false inPendingTransaction=false mDisplayFrozen=true callers=com.android.server.wm.WindowState.access$300:281 com.android.server.wm.WindowState$DeathRecipient.binderDied:3333 android.os.BinderProxy.sendDeathNotice:1206 <bottom of call stack> <bottom of call stack> <bottom of call stack> 
2019-09-15 21:57:11.541 5729-8223/? I/WindowManager: Destroying surface Surface(name=net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity[1456])/@0x5882a80 called by com.android.server.wm.WindowStateAnimator.destroySurface:1903 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:838 com.android.server.wm.WindowState.removeImmediately:2704 com.android.server.wm.WindowState.removeIfPossible:2854 com.android.server.wm.WindowState.access$300:281 com.android.server.wm.WindowState$DeathRecipient.binderDied:3333 android.os.BinderProxy.sendDeathNotice:1206 <bottom of call stack> 
2019-09-15 21:57:11.541 5254-5899/? I/SurfaceFlinger: id=448 Removed net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity[1456]#0 (0/77)
2019-09-15 21:57:11.543 5729-5739/? W/ActivityManager: Force removing ActivityRecord{62ba5c7 u0 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity t6645}: app died, no saved state
2019-09-15 21:57:11.544 5254-5899/? I/SurfaceFlinger: id=445 Removed d2bfb49 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity#0 (1/76)
2019-09-15 21:57:11.545 5729-8223/? V/WindowManager: Changing focus from Window{d2bfb49 u0 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity} to null Callers=com.android.server.wm.WindowState.removeIfPossible:2860 com.android.server.wm.WindowState.access$300:281 com.android.server.wm.WindowState$DeathRecipient.binderDied:3333 android.os.BinderProxy.sendDeathNotice:1206 
2019-09-15 21:57:11.546 5729-5761/? D/WindowManager: reportFocusChangedSerialized, focused=false, inTouchMode=true, win=Window{d2bfb49 u0 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity}
2019-09-15 21:57:11.547 5729-5761/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{d2bfb49 u0 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1140)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3894)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5472)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2019-09-15 21:57:11.551 5254-5254/? I/Layer: id=450 onRemoved Background for -SurfaceView - net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity@3444c43@0[1456]#0 
2019-09-15 21:57:11.551 5254-5254/? I/Layer: id=448 onRemoved net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity[1456]#0 
2019-09-15 21:57:11.551 5254-5254/? I/Layer: id=449 onRemoved SurfaceView - net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity@3444c43@0[1456]#0 
2019-09-15 21:57:11.551 5254-5254/? I/Layer: id=445 onRemoved d2bfb49 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity#0 
2019-09-15 21:57:11.565 5729-5739/? I/WindowManager: Cancelling animation restarting=false, leash=null, surface=Surface(name=AppWindowToken{36acb1d token=Token{c0267f4 ActivityRecord{62ba5c7 u0 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity t6645}}})/@0xb1265cb, parent=Surface(name=Task=6645)/@0xda5fd47
2019-09-15 21:57:11.568 5254-5899/? W/SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{36acb1d token=Token{c0267f4 ActivityRecord{62ba5c7 u0 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity t6645}}}#0
2019-09-15 21:57:11.584 5254-5254/? I/Layer: id=433 onRemoved AppWindowToken{36acb1d token=Token{c0267f4 ActivityRecord{62ba5c7 u0 net.bctank.game/com.google.firebase.MessagingUnityPlayerActivity t6645}}}#0 
2019-09-15 21:57:11.666 5729-6118/? D/GameManagerService: notifyResumePause(). pkg: net.bctank.game, type: 1, isMinimized: false, isTunableApp: false
2019-09-15 21:57:11.667 5729-6118/? D/GameManagerService:   notifyResumePause(). before send intent to GameTools. type:1, pkgName:net.bctank.game, minimized:false
2019-09-15 21:57:11.696 1523-1568/? E/GameTools: DreamToolsEventMgr : java.lang.Exception: onGameResume failed. net.bctank.game process is not founded
2019-09-15 21:57:11.721 1523-1568/? E/GameTools: DreamToolsEventMgr : java.lang.Exception: onGameResume failed. net.bctank.game process is not founded

```

**Comment by markchandler-google** [comment]
Hi @anhnh1721, with out more details of what you are trying todo there is not much we can help you with. Guessing by looking at the logs it seems as if one of the object instances is not being kept alive causing it to be cleaned up (Dead Object Exception). If you can reproduce the crash with the test app we might be able to help more.

**Comment by chkuang-g** [comment]
@anhnh1721 
There is very little clues from the log you gave us.

Could you try to describe more information when this happens?  Here are some starters

- After you install the apk, did it crash 100% everytime when you start the app?
- Could you gradually remove the Firebase plugin you installed and try to narrow down a specific plugin that is causing the crash?
- Could you provide a minimal Unity project for us to look into?

Thank you
Shawn

**Comment by patm1987** [comment]
Hi @anhnh1721 ,

If you can, we'd love to hear from you if you can answer @chkuang-g 's questions or if you've resolved the issues on your own. We'd love to fix the issue, but cannot reproduce it internally without a little more information.

Thanks,
--Patrick

**Comment by anhnh1721** [comment]
I used firebase latest version with unity 2019.3 the error is no longer available. Thank you
