### ISSUE TITLE
com.google.firebase.d: An internal error has occurred. [ Error code:26 ]

### ISSUE THREAD

**Issue by AlexeyGodyaev** [firebase/quickstart-unity#591]
Non-fatal Exception: com.google.firebase.d: An internal error has occurred. [ Error code:26 ]
       at com.google.firebase.auth.api.internal.zzdv.zza(zzdv.java:18)
       at com.google.firebase.auth.api.internal.zzex.zza(zzex.java:3)
       at com.google.firebase.auth.api.internal.zzfa.run(zzfa.java:4)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by AlexeyGodyaev** [comment]
Устройство
Марка: HUAWEI
Модель: HUAWEI Y6s
Ориентация: Вертикальная
Свободная оперативная память: 588.89 MB
Свободное место на диске: 14.79 GB
Операционная система
Версия: 9
Ориентация: Вертикальная
Root-доступ: Нет
Сбой
Дата: 19 февр. 2020 г., 15:18:00

**Comment by paulinon** [comment]
Thanks for reporting this, @AlexeyGodyaev. Could you share a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of your project as well as the steps you've taken before encountering this issue? This way, I can try to reproduce the issue on my end and hopefully find a solution.

**Comment by DellaBitta** [comment]
This seems similar to [Issue 592](https://github.com/firebase/quickstart-unity/issues/592) which has more information.  I'm going to mark this as duplicate for now  If this is indeed a different issue then please create a new ticket with more information around the context of the exception. Thank you!
