### ISSUE TITLE
FirebaseAnalytics.LogEvent() caused SQLite error.

### ISSUE THREAD

**Issue by mskim-dv** [firebase/quickstart-unity#676]
### Please fill in the following fields:

Unity editor version: 2019.3.10f

Firebase Unity SDK version: 6.14.0

Source you installed the SDK (.unitypackage or Unity Package Manager): UPM

Firebase plugins in use (Auth, Database, etc.): 
Auth, Database, Anayltics, Crashlytics, Remote config, Firestore, Cloud messaging, Functions

Additional SDKs you are using (Facebook, AdMob, etc.): GPGS

Platform you are using the Unity editor on (Mac, Windows, or Linux): Windows

Platform you are targeting (iOS, Android, and/or desktop): Android

Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

This stacktrace is triggered when I call FirebaseAnalytics.LogEvent()

```
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: Error inserting period=2680000 preferred_charging_state=1 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1589443587064 required_idleness_state=0 source=16 service_kind=0 target_package=com.google.android.gms persistence_level=1 source_version=201516000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=1339000 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}: com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1417): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at apnp.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):76): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at apne.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):173): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at apne.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):21): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at apne.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):167): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at apjn.run(:com.google.android.gms@201516019@20.15.16 (040400-309763488):8): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at ssd.b(:com.google.android.gms@201516019@20.15.16 (040400-309763488):12): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at ssd.run(:com.google.android.gms@201516019@20.15.16 (040400-309763488):7): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at sye.run(:com.google.android.gms@201516019@20.15.16 (040400-309763488):0): com.google.android.gms.persistent
05-14 17:06:27.074  5255 25542 E SQLiteDatabase: 	at java.lang.Thread.run(Thread.java:764): com.google.android.gms.persistent
```
### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
yes.... perfectly
What's the issue repro rate? (eg 100%, 1/5 etc)
100%

+++ log in Firebase Unity quickstarts
just add Firebase Core and Google Analytics 6.14.0 by UPM
```
05-14 19:07:20.096  3381  3438 I Unity   : Logging a login event. : my.package.id
05-14 19:07:20.096  3381  3438 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35): my.package.id
05-14 19:07:20.096  3381  3438 I Unity   : : my.package.id
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: Error inserting period=7076000 preferred_charging_state=1 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1589450840209 required_idleness_state=0 source=16 service_kind=0 target_package=com.google.android.gms persistence_level=1 source_version=201516000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=3537000 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}: com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1417): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at apnp.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):76): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at apne.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):173): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at apne.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):21): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at apne.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):167): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at apjn.run(:com.google.android.gms@201516019@20.15.16 (040400-309763488):8): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at ssd.b(:com.google.android.gms@201516019@20.15.16 (040400-309763488):12): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at ssd.run(:com.google.android.gms@201516019@20.15.16 (040400-309763488):7): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at sye.run(:com.google.android.gms@201516019@20.15.16 (040400-309763488):0): com.google.android.gms.persistent
05-14 19:07:20.214  5255 19004 E SQLiteDatabase: 	at java.lang.Thread.run(Thread.java:764): com.google.android.gms.persistent
05-14 19:07:23.539  3381  3438 I Unity   : Logging a group join event. : my.package.id
05-14 19:07:23.539  3381  3438 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35): my.package.id
05-14 19:07:23.539  3381  3438 I Unity   : : my.package.id
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: Error inserting period=7070000 preferred_charging_state=1 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService required_network_type=0 runtime=1589450843600 required_idleness_state=0 source=16 service_kind=0 target_package=com.google.android.gms persistence_level=1 source_version=201516000 last_runtime=0 user_id=0 job_id=-1 requires_charging=0 tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG flex_time=3534000 task_type=0 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}}: com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:783): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1548): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1417): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at apnp.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):76): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at apne.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):173): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at apne.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):21): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at apne.a(:com.google.android.gms@201516019@20.15.16 (040400-309763488):167): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at apjn.run(:com.google.android.gms@201516019@20.15.16 (040400-309763488):8): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at ssd.b(:com.google.android.gms@201516019@20.15.16 (040400-309763488):12): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at ssd.run(:com.google.android.gms@201516019@20.15.16 (040400-309763488):7): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at sye.run(:com.google.android.gms@201516019@20.15.16 (040400-309763488):0): com.google.android.gms.persistent
05-14 19:07:23.604  5255 19004 E SQLiteDatabase: 	at java.lang.Thread.run(Thread.java:764): com.google.android.gms.persistent
```

And I'm not sure... but I doubt that it make logging event failed frequently.

**Comment by chkuang-g** [comment]
@mskim-dv 

I saw similar exception by installing Analytics with `.unitypackage` as well so I do not think this is a UPM specific issue.

I did see correlation between this exception and Analytics Android sdk.  I'll forward this information to the team for investigation.

At the meantime, is this blocking you?  From my experience, this exception never occurs after the app launched.

For more detail about this issue, what device and Android version did you use when this occurred?

**Comment by mskim-dv** [comment]
@chkuang-g 

Hello, chkuang-g.
Thank you for anwser :)

No, this bug doesn't occur any crash or freezing. 
And this bug is occured with every LogEvent().
But It is difficult to determine exactly how any side effects.

Here is my device list used for test.
- Galaxy s7 / SM-930F / Android 6
- Galaxy s8+ / SM-955N / Android 9
- Blackberry Key2 / BBF100-6 / Android 8

**Comment by patm1987** [comment]
Thanks for your help tracking this down. I'm removing the needs attention label for now, but feel free to update this bug report with any other information you feel is necessary.

**Comment by chkuang-g** [comment]
@mskim-dv 

It has been awhile and many things has been changed. Unfortunately we were not able to reproduce or track down the cause of this with `6.14.0`. It is unclear to me that if any Android SDK release patched this issue either.

Are you still experience the same issue when you are using later version of Firebase SDK, ex. `7.1.0`?

Shawn
