### ISSUE TITLE
Android app crashes at start because of generated AndroidManifest.xml 

### ISSUE THREAD

**Issue by kjyv** [firebase/quickstart-unity#727]
### Please fill in the following fields:
Unity editor version: 2019.4.1f
Firebase Unity SDK version: at least 6.10, 6.14 and 6.15.1
Source you installed the SDK (.unitypackage or Unity Package Manager): tried both
Firebase plugins in use (Auth, Database, etc.): Auth, Storage
Additional SDKs you are using (Facebook, AdMob, etc.): Mapbox, NatDevice, ARFoundation
Platform you are using the Unity editor on (Mac, Windows, or Linux): Mac
Platform you are targeting (iOS, Android, and/or desktop): Android
Scripting Runtime (Mono, and/or IL2CPP): IL2CPP

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)
With firebase added to the project, the patch manifest option seems to create some invalid configuration. The file is attached.
Basically, there doesn't seem to be a library called VulkanLayerValidationTests on the test device (Samsung S8) but the manifest wants to load it.
If I disable patching the file (and then removing it so Unity uses the generated one), I get a different error about missing the linked in class.

07-06 14:15:30.100 14827 14827 E AndroidRuntime: FATAL EXCEPTION: main
07-06 14:15:30.100 14827 14827 E AndroidRuntime: Process: <our-app-id>, PID: 14827
07-06 14:15:30.100 14827 14827 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{<out-app-id>/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to find native library VulkanLayerValidationTests using classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/<our-app-id>-E6lrNWgH8fpJdswYGmgwGQ==/base.apk"],nativeLibraryDirectories=[/data/app/<our-app-id>-E6lrNWgH8fpJdswYGmgwGQ==/lib/arm64, /data/app/<our-app-id>-E6lrNWgH8fpJdswYGmgwGQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]]
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7050)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unable to find native library VulkanLayerValidationTests using classloader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/<our-app-id>-E6lrNWgH8fpJdswYGmgwGQ==/base.apk"],nativeLibraryDirectories=[/data/app/<our-app-id>-E6lrNWgH8fpJdswYGmgwGQ==/lib/arm64, /data/app/<our-app-id>-E6lrNWgH8fpJdswYGmgwGQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]]
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.NativeActivity.onCreate(NativeActivity.java:161)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7327)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7318)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
07-06 14:15:30.100 14827 14827 E AndroidRuntime: 	... 11 more

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?
Have not tried

What's the issue repro rate? (eg 100%, 1/5 etc)
100%

[AndroidManifest.xml.txt](https://github.com/firebase/quickstart-unity/files/4878803/AndroidManifest.xml.txt)

**Comment by kjyv** [comment]
Ah yes sorry

**Comment by kjyv** [comment]
Never mind, I think I mistook firebase as the origin of the issue.
