### ISSUE TITLE
Crash: java.lang.IllegalStateException: Not allowed to start service Intent 

### ISSUE THREAD

**Issue by go3k** [firebase/quickstart-unity#785]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.7f1
  * Firebase Unity SDK version: 6.15.2
  * Source you installed the SDK: .unitypackage (.unitypackage or Unity Package Manager)
  * Problematic Firebase Component: Messaging (Auth, Database, etc.)
  * Other Firebase Components in use: Analytics (Auth, Database, etc.)
  * Additional SDKs you are using: Facebook (Facebook, AdMob, etc.)
  * Platform you are using the Unity editor on: Mac (Mac, Windows, or Linux)
  * Platform you are targeting: Android (iOS, Android, and/or desktop)
  * Scripting Runtime: IL2CPP (Mono, and/or IL2CPP)

### [REQUIRED] Please describe the issue here:

I did the integration according to this documentation, relevant detail code is under below.

https://firebase.google.com/docs/cloud-messaging/unity/client#configuring_a_custom_entry_point_activity

App crash when resume app form background, crash log is

```
2020-09-18 18:02:39.258 2397-2397/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.camelgames.ig, PID: 2397
    java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE cmp=com.camelgames.ig/com.google.firebase.messaging.MessageForwardingService }: app is in background uid UidRecord{1c036c0 u0a480 CAC  bg:+17m6s865ms idle change:idle procs:1 proclist:2397, seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1688)
        at android.app.ContextImpl.startService(ContextImpl.java:1633)
        at android.content.ContextWrapper.startService(ContextWrapper.java:683)
        at com.camelgames.odyssey.UnityPlayerActivity.onNewIntent(UnityPlayerActivity.java:172)
        at android.app.Activity.performNewIntent(Activity.java:7971)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1407)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1420)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3779)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3791)
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2229)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8034)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

#### Steps to reproduce:

1. Press Home button let app into background
2. Receive a FCM push notification
3. Click the App Icon again.

#### Relevant Code:

		Intent message = new Intent(this, MessageForwardingService.class);
		message.setAction(MessageForwardingService.ACTION_REMOTE_INTENT);
		message.putExtras(intent);
		message.setData(intent.getData());
		startService(message);

**Comment by DellaBitta** [comment]
Hi @go3k,

This appears to be the same as another internal issue that we've been tracking.  It should be fixed in the next release.

**Comment by DellaBitta** [comment]
Hi @go3k,

Version 6.16.0 has been released. It includes a fix for an internally reported issue similar to your reported test case.  I'm going to close this issue for now, but if you continue to have the problem then please re-open it.  Thanks!
