### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Nyankoo** [firebase/quickstart-unity#974]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.21f1
  * Firebase Unity SDK version: 7.1.0
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: InAppMessaging
  * Other Firebase Components in use: Firestore, Analytics, Crashlytics, Remote Config
  * Additional SDKs you are using: AdMob
  * Platform you are using the Unity editor on: Windows
  * Platform you are targeting: Android
  * Scripting Runtime: IL2CPP

### [REQUIRED] Please describe the issue here:

Some of our users getting crashes caused by the InAppMessaging package. When this is happening is currently unknown to us, as we can't replicate this on our end.

The devices the crashes happen on are:
- Huawei P10 lite (Android 8.0.0)
- Samsung Galaxy A51 (Android 10)
- Samsung Galaxy A5(2017) (Android 8.0.0)
- Samsung Galaxy Galaxy S7 (Android 8.0.0)
- Samsung Galaxy Note10 Lite (Android 11)
- Samsung Galaxy A50 (Android 10)
- Samsung Galaxy A21s (Android 10)
- Samsung Galaxy J8 (Android 10)
- Samsung Galaxy S8+ (Android 9)
- Samsung Galaxy A10 (Android 10)
- Xperia 1 II (Android 11)
- Xperia L3 (Android 8.1.0)
- Redmi 8 (Android 9)
- ZTE Blade 10 Vita (Android 9)
- Amazon Fire HD (Android 9)
- Moto C Plus (Android 7.0)
- LG Stylo 5 (Android 10)
- vivo 1904 (Android 9)

#### Steps to reproduce:

Have you been able to reproduce this issue with just the Firebase Unity quickstarts (this GitHub project)?

What happened? How can we make the problem occur?

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
       at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:507)
       at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
       at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
       at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
       at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
       at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
       at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
       at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:395)
       at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:403)
       at com.google.firebase.inappmessaging.CampaignAnalytics$Builder.setClientApp(CampaignAnalytics.java:1049)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createCampaignAnalyticsBuilder(MetricsLoggerClient.java:193)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.createEventEntry(MetricsLoggerClient.java:170)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient.lambda$logMessageClick$1(MetricsLoggerClient.java:126)
       at com.google.firebase.inappmessaging.internal.MetricsLoggerClient$$Lambda$2.onSuccess(:6)
       at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by Nyankoo** [comment]
Possibly related to this?
https://github.com/firebase/firebase-android-sdk/issues/2158#issuecomment-732989095

**Comment by chkuang-g** [comment]
@Nyankoo 

This is odd.  I don't think we provide InAppMessaging API in our Firebase Unity SDK. Are you using InAppMessaging in your app? If so, is your project directly use native Android SDK?

If not, the only possible reason is that one of those Firebase product you used, a.k.a `Firestore, Analytics, Crashlytics, Remote Config`, is calling InAppMessaging API internally.  From the functionality of those products and InAppMessaging, it does not make too much sense though.

https://github.com/firebase/firebase-android-sdk/issues/2158#issuecomment-732989095 looks like an issue for Firebase Performance, which is not available in Unity SDK either.  Also that is not related to InAppMessaging.

Could you provide a bit more information about how InAppMessaging got into your app?

Shawn

**Comment by Nyankoo** [comment]
@chkuang-g Yes, we're using the native Android SDK directly by adding the correct dependencies through the External Dependency Manager.

**Comment by chkuang-g** [comment]
@Nyankoo

Ah I see.  
Currently Firebase Unity SDK does not fully support this use-case.  It is hard for me to tell if this is an Android SDK issue or something related to the whole C++/Unity architecture. I'm most concerned about the life-cycle of the FirebaseApp instance from Android.

Let clarify several things
- Did this started to happen after you upgraded from a certain version of Firebase Unity SDK? If so, which version did you upgrade from?
- What is the version of InAppMessaging which you added through EDM4U? Note that Firebase Unity SDK would deliver the Android dependencies which work the most stable together.  It is hard to tell if your InAppMessaging version is compatible to `7.1.0`
- Did you see any error when EDM4U tried to resolve dependencies?
- Perhaps tell us a bit more about how your project use InAppMessaging along with other Firebase component through Unity SDK. Did you create C# FirebaseApp before or after you started to call InAppMessaging API?

Also, I would recommend you to open a ticket at [firebase-android-sdk repo](https://github.com/firebase/firebase-android-sdk/issues) and point to this issue as a reference.

**Comment by Nyankoo** [comment]
@chkuang-g Thank you for the detailed explanation!

Do I file a feature request directly here in this repo, or somewhere else?

About your questions:
- This started after we published our app, but not for all users. We didn't encounter this while testing (before and after release), so this sounds more like a device issue.
- We added version 19.1.4 of the InAppMessaging SDK through EDM4U. We checked the Android SDK's changelog for this, looking for the same versions the Unity SDK uses.
- No errors from EDM4U when resolving.
- We're only using the InAppMessaging SDK to receive automated messages from the "In-App Messaging" dashboard on the Firebase backend. Then instead of using Android's `public void messageClicked` event handler, we process deep-link information depending on which button of the message was tapped. More details about this can be found here: https://www.robinryf.com/blog/2020/01/04/firebase-in-app-message-in-unity.html

Another note that could be important is that we're getting the same debug output ("Starting InAppMessaging runtime...") on our test devices as mentioned in the Android documentation here: https://firebase.google.com/docs/in-app-messaging/get-started?authuser=0&platform=android#get_your_apps

**Comment by chkuang-g** [comment]
Thank you for the information.

I'll forward this to the team.

**Comment by vimanyu** [comment]
Hi @Nyankoo,
Do you know if your application is directly or transitively pulling in a version of protobuf libraries (protobuf-javalite or any other protobuf libraries) that is different from Firebase protobuf library version?

For FIAM 19.1.4, we are using 3.14.0.
```
|    |    +--- com.google.firebase:protolite-well-known-types:17.1.1
|    |    |    \--- com.google.protobuf:protobuf-javalite:3.14.0
```

**Comment by Nyankoo** [comment]
@vimanyu Is there a way to check this somewhere in the final .aab file (or somewhere else)?

**Comment by vimanyu** [comment]
If you are using gradle for your application, you could run the following to get list of dependencies.
```
# assuming app is the name of the project
./gradlew app:dependencies
```

**Comment by Nyankoo** [comment]
@vimanyu Where do I execute this exactly? We're using gradle, but Unity handles everything for us.

**Comment by Nyankoo** [comment]
@vimanyu The above dependencies are the only ones I can see in the dependency tree after exporting to Android Studio.

**Comment by vimanyu** [comment]
Thanks for confirming. It does seem like something tried to get javalite 3.11.0 but was bumped up to 3.14.0. 
Another clarification, is the error 100% reproducible on the devices listed in the original post?

**Comment by Nyankoo** [comment]
@vimanyu We sadly don't have any of the listed devices on hand to test this. The list comes directly from Crashlytics (user devices).
