### ISSUE TITLE
[Bug] Storage GetBytesAsync crash for gzip-encoded file

### ISSUE THREAD

**Issue by vnorilo** [firebase/quickstart-unity#986]
### [REQUIRED] Please fill in the following fields:

  * Unity editor version: 2019.4.14f1
  * Firebase Unity SDK version: 6.15.2 (also tried 7.1.0)
  * Source you installed the SDK: Unity Package Manager
  * Problematic Firebase Component: Storage
  * Other Firebase Components in use: Auth, Database, RemoteConfig, Messaging 
  * Additional SDKs you are using: none
  * Platform you are using the Unity editor on: Mac
  * Platform you are targeting: Android
  * Scripting Runtime:IL2CPP

### [REQUIRED] Please describe the issue here:

Android client crashes when calling `GetBytesAsync` for a Storage reference that points to a gzip-encoded file. In editor, the method works fine and provides the compressed stream bytes.

#### Steps to reproduce:

What happened? How can we make the problem occur?

- Upload and gzip-encode a file to Firebase storage with e.g. `gsutil cp -Z <local-file> <gs://remote-file>`
- Call `FirebaseStorage.DefaultInstance.GetReference(<remote-file>).GetBytesAsync(1000000)`

On Android device, the call will always crash, even when the file is much, much smaller than the provided limit:

```
2021/03/09 10:16:11.359 6904 7586 Error StorageException StorageException has occurred.
2021/03/09 10:16:11.359 6904 7586 Error StorageException An unknown error occurred, please check the HTTP result code and inner exception for server response.
2021/03/09 10:16:11.359 6904 7586 Error StorageException  Code: -13000 HttpResult: 200
2021/03/09 10:16:11.359 6904 7586 Error StorageException The maximum allowed buffer size was exceeded.
2021/03/09 10:16:11.359 6904 7586 Error StorageException java.lang.IndexOutOfBoundsException: The maximum allowed buffer size was exceeded.
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at com.google.firebase.storage.internal.cpp.CppByteDownloader.doInBackground(CppByteDownloader.java:55)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at com.google.firebase.storage.StreamDownloadTask.run(com.google.firebase:firebase-storage@@19.1.1:179)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7(com.google.firebase:firebase-storage@@19.1.1:1072)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at com.google.firebase.storage.StorageTask$$Lambda$12.run(Unknown Source:2)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at java.lang.Thread.run(Thread.java:784)
```

My suspicion is that the Android client allocates the byte buffer based on file size in storage. However, the fetch fails to send `accepts: gzip` to the server, which should cause automatic decompression in Google Cloud Storage and the resulting uncompressed stream is too big to fit the buffer, whose size may be based on the compressed size.

**Comment by vimanyu** [comment]
Hi,
I just tried this real quick in our (Unity Storage quickstart)[https://github.com/firebase/quickstart-unity/tree/master/storage/testapp] and could not reproduce it.
Here are the steps I tried,
- Unity 2020.1.7f1 and FirebaseStorage 7.1.0
- Uploaded "test.txt", "test.zip" and "test.gz" (created with `gzip -c test.txt > test.gz`) to storage bucket via the Firebase console web interface.
- Downloaded bytes for each of them in Editor and on my Android 8.0 device and I didn't see any crashes.

Could you verify if our quickstart example crashes for you on Android too? If yes, could you try enabling debug logging and running once again,
```
Firebase.LogLevel logLevel = Firebase.LogLevel.Debug;
```

**Comment by vnorilo** [comment]
Thank you for the reply! Did you also set the content encoding metadata to gzip for the gz stream? I'm not sure if that can be done from the console web interface. I will check the quickstart next week. Thanks again!

**Comment by vimanyu** [comment]
I see. I didn't try setting the content encoding metadata though the file type is identified as "application/x-gzip
" in the console. It will be quicker for us to debug if we can reproduce this easily in our quickstarts.

**Comment by vnorilo** [comment]
Hi @vimanyu ,

Instructions for reproducing the crash with the quickstart-unity project. You do not need to make any changes.

- Upload file to storage with gzip encoding. One way to do this is to use `gsutil cp -Z <local-file> <remote-file>`.
- You can verify that the file opens from Firebase console. In this instance the compressed file is automatically decompressed.
- Launch quickstart-unity storage sample
- Enter the remote path to the quickstart "Storage Location" field.
- Press "Download Bytes"
- Expected result: get the gzip-encoded bytestream

This works as expected in Editor, but produces a crash as shown on the top of this thread on Android. Tested with trunk on this repo and the linked Firebase SDK 7.1.0 for XCode 12 and dotnet4. Unity 2019.4.14f1.

If you omit `-Z` from the gsutil upload command, the file is not encoded or compressed, and the setup works on both platforms. Gzip encoding is mandatory for us because it reduces some storage file sizes by a factor of 50:1, but because of this bug we cannot use the correct encoding metadata, and have to communicate encoding out-of-band.

**Comment by cynthiajoan** [comment]
Hi @vnorilo, I followed your repro steps, use gsutil with -Z to upload a file, and download bytes with no issue. Is there any other steps that I should pay attention to? How big is your file?

**Comment by vnorilo** [comment]
Hi Cynthia! Thanks for picking this up. Perhaps it results from a combination of Firebase SDK and Android system. As I speculated on top of this thread, Google Cloud will automatically decompress bytestreams when the http request doesn't have `accepts: gzip` . If Firebase SDK allocates the buffer based on file size but receives an uncompressed stream, that would explain this behavior.

At this point all I can really do is to try to make sure all the details are correct. Here I've got two files, `gs://musopia-donotuse/readme.md` and `gs://musopia-donotuse/readme-identity.md`. The former is uploaded with -Z, the latter not.

Metadata as per gsutil:
```
gs://musopia-donotuse/readme.md:
    Creation time:          Wed, 17 Mar 2021 13:34:30 GMT
    Update time:            Wed, 17 Mar 2021 13:34:43 GMT
    Storage class:          REGIONAL
    Cache-Control:          no-transform
    Content-Encoding:       gzip
    Content-Length:         251
    Content-Type:           application/octet-stream
    Metadata:               
        firebaseStorageDownloadTokens:defce827-c865-4ad4-974d-5cacb0c1134d
    Hash (crc32c):          vMMJYw==
    Hash (md5):             8qD9Edh2x6aA9aC+AV6/Fg==
    ETag:                   CIaejNe4t+8CEAI=
    Generation:             1615988070223622
    Metageneration:         2
```

```
gs://musopia-donotuse/readme-identity.md:
    Creation time:          Wed, 17 Mar 2021 13:35:28 GMT
    Update time:            Wed, 17 Mar 2021 13:35:53 GMT
    Storage class:          REGIONAL
    Content-Length:         374
    Content-Type:           application/octet-stream
    Metadata:               
        firebaseStorageDownloadTokens:fea51e87-425a-45f9-8ab1-8762a6aa6d29
    Hash (crc32c):          F4i+2w==
    Hash (md5):             3tXAmpXvDTWnVfcuy6AM2g==
    ETag:                   CPGc5/K4t+8CEAI=
    Generation:             1615988128337521
    Metageneration:         2
```

I've attached screenshots of the quickstart app on the crashing device and the device system info screen.

Crash on downloading readme.md:
![Screenshot_20210323-085618](https://user-images.githubusercontent.com/14020514/112107158-44886e80-8bb7-11eb-9f67-553090fa63ab.jpg)

Fine while downloading readme-identity.md (after correcting typoed url :P )
![Screenshot_20210323-085908](https://user-images.githubusercontent.com/14020514/112107197-51a55d80-8bb7-11eb-946f-ee580fea58e7.jpg)

Device:
![Screenshot_20210323-090043](https://user-images.githubusercontent.com/14020514/112107258-6124a680-8bb7-11eb-8968-d0048b175cf6.jpg)

Thanks again!

**Comment by cynthiajoan** [comment]
Hi @vnorilo, I managed to repro the issue both with our unity testapp and android testapp, our team will be looking into solve the issue.

**Comment by chkuang-g** [comment]
@schmidt-sebastian 

Unity `StorageReference.GetBytesAsync()` API is calling into [StorageReference.getStream()](https://firebase.google.com/docs/reference/android/com/google/firebase/storage/StorageReference#getStream(com.google.firebase.storage.StreamDownloadTask.StreamProcessor)) through [C++ API](https://github.com/firebase/firebase-cpp-sdk/blob/0c8c8b29bc2d62d66c6ac49ff2c3fb04f815a687/storage/src/android/storage_reference_android.cc#L447)

C++ code did not check `StreamDownloadTask.getTotalByteCount()` at all to throw any exception.

Judge by the user's callstack, this seem to be thrown from native Android SDK.
```
2021/03/09 10:16:11.359 6904 7586 Error StorageException java.lang.IndexOutOfBoundsException: The maximum allowed buffer size was exceeded.
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at com.google.firebase.storage.internal.cpp.CppByteDownloader.doInBackground(CppByteDownloader.java:55)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at com.google.firebase.storage.StreamDownloadTask.run(com.google.firebase:firebase-storage@@19.1.1:179)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7(com.google.firebase:firebase-storage@@19.1.1:1072)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at com.google.firebase.storage.StorageTask$$Lambda$12.run(Unknown Source:2)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2021/03/09 10:16:11.359 6904 7586 Error StorageException 	at java.lang.Thread.run(Thread.java:784)
```

Perhaps it works with  [StorageReference.getBytes()](https://firebase.google.com/docs/reference/android/com/google/firebase/storage/StorageReference#getBytes(long)) but not [StorageReference.getStream()](https://firebase.google.com/docs/reference/android/com/google/firebase/storage/StorageReference#getStream(com.google.firebase.storage.StreamDownloadTask.StreamProcessor)) ?

**Comment by chkuang-g** [comment]
Further dig:

The exception is thrown from [this code](
https://github.com/firebase/firebase-cpp-sdk/blob/0c8c8b29bc2d62d66c6ac49ff2c3fb04f815a687/storage/src_java/com/google/firebase/storage/internal/cpp/CppByteDownloader.java#L55)

This implies that `StreamProcessor` cannot get anything from the `InputStream` if the file is a `gzip` file.

**Comment by chkuang-g** [comment]
Update:

Tried [Android testapp](https://github.com/firebase/quickstart-android/blob/master/storage/app/src/main/java/com/google/firebase/quickstart/firebasestorage/java/MyDownloadService.java#L103) and it does not seems like anything odd about the value in `bytesDownloaded`. `getTotalByteCount()` returns `-1` as @schmidt-sebastian mentioned in https://github.com/firebase/firebase-android-sdk/pull/2618. But that should not cause the exception to be thrown in [C++ SDK](https://github.com/firebase/firebase-cpp-sdk/blob/0c8c8b29bc2d62d66c6ac49ff2c3fb04f815a687/storage/src_java/com/google/firebase/storage/internal/cpp/CppByteDownloader.java#L55)

Will need to further investigate into the issue.
